### ISSUE TITLE
Don't apply "Comment: Use `//` comments everywhere" rule to .css files

### ISSUE THREAD

**Issue by mcandre** [brigade/scss-lint#225]
Many CSS parsers do not accept `//` comments, instead using `/* ... */`.

In the future, could scss-lint automatically exclude this rule from `.css` files?

**Comment by janaspage** [comment]
If I disable csslint in my SublimeLinter user settings, I still get the "Use `//` comments everywhere" warning in my CSS files. 
```
        "linters": {
            "csslint": {
                "@disable": true,
                "args": [],
                "errors": "",
                "excludes": [],
                "ignore": "",
                "warnings": ""
            },
            "eslint": {
                "@disable": false,
                "args": [],
                "excludes": []
            },
            "jshint": {
                "@disable": false,
                "args": [],
                "excludes": []
            },
            "json": {
                "@disable": false,
                "args": [],
                "excludes": [],
                "strict": true
            },
            "jsxhint": {
                "@disable": false,
                "args": [],
                "excludes": []
            },
            "scss": {
                "@disable": false,
                "args": [],
                "exclude-linter": "",
                "excludes": [],
                "include-linter": ""
            }
        },
```

**Comment by jaepage** [comment]
This isn't working for me. 

I've tried formatting as: 

```
linters:

  Comment:
    severity: warrning
    exclude:
      - '**/*.css'
```

And as: 

```
linters:

  Comment:
    severity: error
    exclude: '**/*.css'
```

I can see the gutter light toggle between yellow and red, but it won't disappear from my `/* … */` comments in CSS files. 

I know I can separately run a CSS linter, but it would seem preferable to run a single linter for Sass and CSS for consistency. 

Thank you. 

- macOS 10.13.3 High Sierra
- Sublime Text 3.0

**Comment by srawlins** [comment]
Hi @jaepage, first of all you might get more response by opening a new bug or commenting on an open bug.

Secondly, what is the integration between scss-lint and Sublime that draws the "gutter light"? I'm not aware of one. Does the integration respect `.scss-lint.yml`? What does the tool think of as "the current directory" in order to find `.scss-lint.yml`? Or are you using a `.scss-lint.yml` in your home directory?

**Comment by srawlins** [comment]
To remove a layer of complexity, can you just run the `scss-lint` command line tool and verify that it is still linting your *.css files with the Comment linter?
