### ISSUE TITLE
Regexp for modified BEM format

### ISSUE THREAD

**Issue by gmoulin** [brigade/scss-lint#240]
Hi,
I want to enforce a modified BEM format and I do not find how using the regexp format.
Furthermore I want to only enforce selectors names and not variables or mixins names.

In the code I saw a "SelectorFormat" rule but there is no mention of it in the example config yml file.

my format : blockSomething__elementSomethingElse--modifierOtherThing
Basically I want to permit camelCase in css classes.

I have "CapitalizationInSelector" to false and no selector errors are reported, but format enforcing is still active for variables and mixins.

I tried 
  NameFormat:
    enabled: true
    convention: '?!(-{3}|_{3}|[^_]_[^_])' 
but the program choke on it. (need to negate the BEM modified regexp for =~ use, BEM rule using !~)

I do not know if the combination of  "NameFormat" with BEM and "CapitalizationInSelector" is the correct way to go either.

Any idea ?

**Comment by TheDutchCoder** [comment]
For anyone interested, I'm using the more popular BEM notation (e.g. foo__bar--baz) and the following RegEx works on a good amount of cases:

https://regex101.com/r/yP0eM7/1

Cheers.
