### ISSUE TITLE
Invalid US-ASCII difference just changing @charset "utf-8" to @charset 'utf-8'

### ISSUE THREAD

**Issue by felquis** [brigade/scss-lint#291]
When I run `scss-lint app/css/**/*.scss`

The first log line is: `app/css/_background.scss:1 [E] Unable to parse SCSS file: Invalid US-ASCII character "\xC3"`

My first line in `_background.scss` is `@charset 'utf-8';`

If I change it to `@charset "utf-8";` the first log becomes `app/css/_background.scss:1 [W] StringQuotes: Prefer single quoted strings`

So, for now I changed my `StringQuotes` option to `enabled: false`

As our team speak Brazilian Portuguese, we have a lot of `São, Padrão, Saúde` in the code.

---

System OSX Yosemite,
ruby -v `ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-darwin14.0]`.
scss-lint --version `scss-lint 0.30.0`

**Comment by aju** [comment]
Hi
I have same issue I run scss-lint inside docker-container build with this image:
https://hub.docker.com/r/shawnzhu/ruby-nodejs/

I got error:
`[E] Unable to parse SCSS file: Invalid US-ASCII character "\xC2"`

`ruby 2.1.1p76 (2014-02-24 revision 45161) [x86_64-linux]`
`Sass 3.4.18 (Selective Steve)`
`scss-lint 0.41.0`

output of `file -bi`
`text/plain; charset=utf-8`

In addition when I run scss-lint on this file from my OS (osX) it works (I get no errors).

**Comment by aju** [comment]
Adding for docker fixed issue
```
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8
```

This is probably solution for this issue.

**Comment by sds** [comment]
Thanks for reporting your findings, @aju. I'm sure it will help others.

**Comment by anahiruiz** [comment]
Hey, i got a issue similar to the first one, can you help me, the error is this:

Error: Invalid US-ASCII character "xC3" on line 5 of /vagrant/htdocs/assets/sass/archivo.scss
1: //-----------------------------------
2: //asdfasdf
3: // Nombre : archivo.scss
4: //
5: // Ubicación : /public/assets/scss/archivo.scss

I know that the error its the accent, I changed it and it works, but that i think is just a workaround, i want it to change it to utf-8 but i don't know where to do this, can you tell me?
