### ISSUE TITLE
Invalid configuration: private method `load' called for Psych:Module

### ISSUE THREAD

**Issue by kchan825** [brigade/scss-lint#324]
Was trying to intrgrate with ST3 but get no response.
Try to do it through command line but also not working and displayed the titled error message
- Running on Mac Yosemite
- ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
- Sass 3.4.9 (Selective Steve)
- scss-lint 0.31.0

**Comment by Raffaele** [comment]
I tried to remove gem, but the answer of my system was:
gem "psych" cannot be uninstalled because it is a default gem

**Comment by cH40z-Lord** [comment]
@Raffaele I don't know the exact answer to your question as I'm not a Ruby nor Gem expert but it is possible to just install v2.0 side-by-side to your current installed version. In order to make it work for me I just ran 
```
gem uninstall psych
gem install psych -v 2.0
```

 and then  `gem list --local | grep psych` then shows the following:

```bash
➜  some_folder git:(master) ✗ gem list --local | grep psych
psych (2.0.8, 2.0.0)
```

**Comment by brunowego** [comment]
:+1:

**Comment by apfelbox** [comment]
Everybody who is still seeing this error:

```
gulp update --system
```

Could help. This was probably an issue in ruby gems itself (see here for a more detailed discussion https://github.com/bbatsov/rubocop/issues/1510)
