### ISSUE TITLE
Enforce use of asset helpers provided by sass-rails

### ISSUE THREAD

**Issue by digitalvapor** [brigade/scss-lint#370]
Do any of you know how to implement a [scss-lint](https://github.com/causes/scss-lint) linting rule to use the sass-rails [features](https://github.com/rails/sass-rails#features)? Or more generally, how to expand upon [urlformat](https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#urlformat)?

Thanks in advance

**Comment by sds** [comment]
Hey @digitalvapor,

I'm not sure I understand what you're asking here. Can you be more specific about what feature you would like to see the `UrlFormat` linter support?

**Comment by digitalvapor** [comment]
@sds A simple example would be to always use `image-url` instead of `url`. This example could be for someone who uses `sass-rails`'s [asset helpers](https://github.com/rails/sass-rails#asset-helpers).

**Comment by sds** [comment]
So you're not asking for a change to the `UrlFormat` linter (as that only deals with `url`). You're looking for a linter that enforces the use of the `image-url` helper over `url` wherever it makes sense to do so.

You need to provide a specific set of criteria for what you are looking for here. An enumerated list of cases the linter should detect would be useful.

I'm open to a pull request for this, but won't have time to get to it soon. It should be nested under a new `Rails` namespace (see the `Compass` linters namespace for an example) as it is Rails-specific.

**Comment by digitalvapor** [comment]
@sds Okay, thanks for helping me better specify this, and to know what is required for such a pull request. I'll try my hand at it this week.

**Comment by sds** [comment]
Without a specific list of cases that this proposed linter to support, I'm closing this issue. Feel free to reopen once you have a pull request prepared or proper list of cases it should handle. Thanks!

**Comment by mockdeep** [comment]
Just came across this. I think it would be pretty handy to have a rule such as this, since we've run into it a few times. I could see either looking for specific selectors ('background', 'cursor' for ours) or just any url that ends in an image format ('jpg', 'png').

**Comment by sds** [comment]
Given that `scss-lint` now supports plugins, and given that this is Rails-specific, I think it makes sense for this to be part of a plugin and not built in to the core.

**Comment by mockdeep** [comment]
Would it make sense to do like rubocop and have a `RunRailsLints` option?
