### ISSUE TITLE
Add option to NestingDepth to ignore parent reference suffixes

### ISSUE THREAD

**Issue by entipe** [brigade/scss-lint#384]
As you may know, since SASS 3.3.0
("The parent selector, &, can be used with an identifier suffix..." http://sass-lang.com/documentation/file.SASS_CHANGELOG.html#smaller_improvements_2)
we can use the ampersand character (&) to build compound selectors.

This is quite usefull if you use BEM principles for writing your classnames selectors.

Take a look at this SASS/SCSS example:

.block {
    &--state {
        color: blue;
    }
}

That will compile to the following CSS:

.block--state {
    color: blue;
}

When I run CSS Lint on my SCSS source code, it considers that I'm using nesting while in reality I'm not.
It could look like nesting but in fact, I'm just concatenating several string into a single classname.
Do you consider this as an issue ?

**Comment by sds** [comment]
Hey @entipe, thanks for raising this issue.

I agree that in this particular case the resulting code generated is not actually nested, but I believe the intent of the `NestingDepth` linter is also to help keep your SCSS code "flat". Thus even though introducing nesting doesn't really add another level of actual nesting, it's still desirable from a readability perspective to keep the amount of syntactical nesting in your SCSS code limited. The deeper your selectors are written the harder they can be to read.

Having said that, I would be open to a pull request adding an option to ignore these sorts of selectors. It would have to handle edge cases like `&--state, .some-nested-class { ... }` (which you would hopefully never write but nonetheless `scss-lint` would need to handle them).

**Comment by JohnAlbin** [comment]
+1 to this feature.

Though, I'm sad to report, I _have_ written a selector like `&--state, .js-added-class-on-parent & { ... }`. Not exactly the selector you mentioned, but pretty close.

**Comment by nenadjelovac** [comment]
+1

This should also apply to `&:hover`, `&:active`, `&:focus` and other pseudo classes.

**Comment by marcobiedermann** [comment]
+1

**Comment by SaltPacket** [comment]
+1

**Comment by sds** [comment]
Implemented in #490.
