### ISSUE TITLE
Allow all conventions of SelectorFormat with NameFormat

### ISSUE THREAD

**Issue by masi** [brigade/scss-lint#387]
Currently I am allowed to use camel case for CSS selectors, but not for variables and functions.

So please, add all options used by SelectorFormat to NameFormat: snake_case, camel_case, hyphenated_BEM.

Regards,
Masi

Sidenote: The explanation "Using lowercase with hyphens in CSS has become the de facto standard" is strange. The SASS features dealt with by NameFormat will never appear in the generated CSS.

**Comment by sds** [comment]
I don't think `hyphenated_BEM` makes sense for a variable name, as it is a convention that explicitly applies to selectors.

This actually points out an issue with `NameFormat` which hasn't been addressed, which is that it exposes `BEM` as a naming convention option, but that doesn't really make sense for reasons already mentioned. I think this was just an oversight when it was first implemented.

`NameFormat` should expose `snake_case` and `camel_case` as options, and should not expose anything `BEM`-related.

**Comment by masi** [comment]
Actually I have no idea what BEM is. I just copied all the available options :)

**Comment by sds** [comment]
Added `snake_case` in 21be0e3, `camel_case` in a2ddd68, and removed `BEM` in f73135a.

**Comment by lencioni** [comment]
@sds I just noticed this now when upgrading to the latest scss-lint, but at Brigade we were relying on the `BEM` option of `NameFormat`, specifically for some placeholder names, but also in some local variable names. It is nice for these names to match up conceptually with the selector format we are using.

I'm going to replace it with this regex I just cooked up for now `^[a-z0-9][a-z0-9-]*(?:__[a-z0-9-]*)?$`, but it would actually be nice to have the same options here as we do for `SelectorFormat`. Thoughts?

**Comment by sds** [comment]
I think part of my desire to remove it entirely was because it felt weird to apply a convention intended for selectors to variables. Placeholders I guess would still be valid.

Having said that, even if we added it back, we would still need to differentiate between `hyphenated_BEM` and `strict_BEM`.
