### ISSUE TITLE
Add node-sass support

### ISSUE THREAD

**Issue by FloNeu** [brigade/scss-lint#418]
Hi, there! First thanks for your project, using it a lot and love it! Normally it wouldn't be an issue, but i currently wanted to use scss-lint/scss on my work machine were i am not allowed to install a lot of stuff.   I got Node, but they won't give me ruby so i can't use your tool as it expects ruby/sass in path. But recently ran into grunt-sass which uses node-sass lib and removes this dependency.

Would it be a great deal to include an option to use this lib instead orginal ruby sass?
All the best, Flo

**Comment by lencioni** [comment]
Hi Flo, thanks for your interest in scss-lint! Unfortunately, this project is deeply tied to the Ruby Sass implementation and we have no plans of working on a node version. There is a little more information on this topic in #397.

I think it would be great if libsass or a project like it exposed an AST that projects like Ruby Sass and scss-lint could rely on, which would make a node version of scss-lint a lot more practical, but I don't expect that to happen very soon.

**Comment by FloNeu** [comment]
ok. thx, anyway. Will  try harder to get ruby installed then :) g
