### ISSUE TITLE
BEM lint should allow block's/element's boolean modifier in shorthand.

### ISSUE THREAD

**Issue by christophercochran** [brigade/scss-lint#419]
Hi, I wouldnt consider myself a BEM expert, and fairly new to using it, but currently the BEM lint only allows block's/element's boolean modifier in key-value format.

For example:
block-name_mod-name_mod-val // allowed
block-name_mod // not

block-name__elem-name_mod-name_mod-val // allowed
block-name__elem_mod // not

Shouldn't block-name_mod  and block-name__elem_mod be allowed? Or in writing BEM when using a modifier shouldn't it always be in key-value format?

**Comment by sds** [comment]
Hey @christophercochran,

It sounds like you are trying to use the `hyphenated_BEM` convention, not `BEM`? See the discussion in #335 for more information.

Others have been tripped up by this as well, so we may call greater attention to this by renaming `BEM` to `strict_BEM`.

**Comment by christophercochran** [comment]
@sds From my understanding hyphenated_BEM is for writing  BEM like classes like:
block-name--mod 
block-name__elem--mod

where the modifier is delimited by a '--' (double hyphen) instead of '_' (single underscore).

block-name_mod
block-name__elem_mod
 
is following BEM naming convention set by BEM (https://github.com/bem/bem-naming/blob/master/README.md) and would use a single underscore instead of the double hyphen, so should still be within the convention of BEM and not hyphenated_BEM.


block-name_modifier_value
block-name__elem_modifier_value

are currently allow, but sometimes is simpler to just write block-name_mod. Unless I am wrong and block-name_mod is not allowed, but in the link above it seems that it should be.

**Comment by sds** [comment]
It seems like your understanding is correct. Unfortunately, our team does not use `strict_BEM` ourselves, but `hyphenated_BEM`, so I'm not familiar enough with the definition of `strict_BEM` to really speak to this issue.

The original regex was provided by @mrpavlikov, who I believe is also using `strict_BEM`. @mrpavlikov, can you speak to this issue at all?

@christophercochran if you provide me a modified regex that matches the cases you expect and include some tests, I would happily merge a pull request. Thanks!

**Comment by mrpavlikov** [comment]
Hello everyone!

> Or in writing BEM when using a modifier shouldn't it always be in key-value format?

Yes, correct, only key-value pair, like in when you are writing css you writes what property will have which value. Same applies to modifiers, you are saying what will be modified and which way. Check this out: https://en.bem.info/method/definitions/#modifiers-for-blocks

> A modifier has a name and a value.

**Comment by christophercochran** [comment]
@mrpavlikov Thank you for your explanation. I saw one mention of boolean statements, but now that I think of it, in the world of CSS, these would be few anyways, and having the name and value does give more detail into what the modification is. Thank you again!
