### ISSUE TITLE
Publish latest to Ruby Gem

### ISSUE THREAD

**Issue by imcnally** [brigade/scss-lint#420]
Hey @sds,

Could you publish the latest version to Ruby Gems? It's at 0.35.0 right now.

Thanks!

**Comment by sds** [comment]
Version [0.37.0](https://rubygems.org/gems/scss-lint/versions/0.37.0) is already out, and 0.36.0 was released on April 8th.

**Comment by imcnally** [comment]
:+1: thanks!
