### ISSUE TITLE
Add property_linespace_threshold_count to PropertySortOrder

### ISSUE THREAD

**Issue by ndarville** [brigade/scss-lint#421]
[I love `PropertySortOrder`](https://github.com/hafniatimes/hafniatimes.github.io/commit/11b662bbcaa5e015402a13d3053c799331bc784b)—but the rule creates more clutter than it removes by flagging un-linespaced properties, when the total number of properties in a rule (ie `p { … }`) is `<=3`.

IMO, the rule should have a `property_linespace_threshold_count` (with a much better name)—with a default of `3`.

With that, the rule will be unequivocally great. :)

**Comment by sds** [comment]
Implemented in 92c0c62d3594b61e65b7797f8262f7fc6abf779d.

**Comment by ndarville** [comment]
Awesome, thanks so much. :+1:
