### ISSUE TITLE
Include "clean" files in report output

### ISSUE THREAD

**Issue by edendramis** [brigade/scss-lint#430]
I'm writing an [HTML reporter](https://github.com/edendramis/scss-lint-html-reporter) to go along with your linter, and I would love to be able to report the number of files that were linted and passed the lint inspection.

Thanks for making such a great tool!

**Comment by srawlins** [comment]
This would require new options to the scss-lint script. Examples of current options like this include:

* GNU diff has `--brief` to "only report when files differ" and `--report-identical-files` to "report when two files are the same."
* GNU grep has `--files-without-match` and `--files-with-matches`.

Perhaps scss-lint could have options `--files-without-lint` and `--files-with-lint`?

**Comment by srawlins** [comment]
Or actually... it's just a reporter. I've opened #527 which gives reporters access to the list of files that were linted.

**Comment by sds** [comment]
Implemented in #527.
