### ISSUE TITLE
Re-add support to lint content not available as a file

### ISSUE THREAD

**Issue by teoljungberg** [brigade/scss-lint#435]
Before 0.35.0 we could send in strings, an array of strings to be more precise,
into `SCSSLint::Runner#run` and get back the violations for that file. But,
since 0.35.0 shipped, all arguments given to `SCSSLint::Runner#run` must be
actual files. Sadly we don't have access to the actual files in [HoundCI](https://houndci.com) which
locks us into to not being able to upgrade to 0.35.0 and onwards.

Could we re-add support to being able to lint content of that does not come from files?

**Comment by teoljungberg** [comment]
I'll gladly help out doing this btw

**Comment by sds** [comment]
Hey @teoljungberg,

I didn't realize HoundCI was using `scss-lint` in this manner. Can you elaborate on why passing the file directly is not possible?

The issue here is that the entire linting framework assumes a lint is associated with a file, so your lint warnings/errors will have to have some dummy filename in them if you're going to get this to work. Why not just write a temporary file?

I suppose I'm not against adding support for this (I didn't realize this was possible before, so I'm not sure what exactly changed), but I'm wary of introducing a hack for a use case easily solved by passing through temporary files.

**Comment by teoljungberg** [comment]
We could re-write the actual linting to use temporary files, but I think it would be nicer to support both actual files and content of files. Since it seems to be baked in https://github.com/brigade/scss-lint/blob/b0de02f59ec5c376e2e5d73e673ffea96e9dd826/lib/scss_lint/engine.rb#L20-L24

**Comment by sds** [comment]
That functionality was added so we can easily write specs for linters, but you're right that it shouldn't be too bad to support files and raw strings.

I'd like to have the `Runner` class act as the main point of contact between HoundCI and `scss-lint`'s engine. I believe the best way to support what you're asking is to add support to `Runner#run` to accept an options hash that takes either `files` or `sources` as a key, and then have the `Runner` do the rest. Make sense?

**Comment by teoljungberg** [comment]
I see, that makes sense.

Having `Runner` being the consumed API sounds like a good idea, that's
what we're using in Hound anyhow. I like the interface of `files` and
`sources` aswell.

**Comment by franzheidl** [comment]
+1 for support of linting strings.
Would be great to use scss-lint for things like text editor/ide plugins to lint the current contents of a file, no matter whether the current state of the file is saved or not.

**Comment by teoljungberg** [comment]
@sds Has there been any movement on this subject?

**Comment by sds** [comment]
Hey @teoljungberg,

Apologies, I realize we kind of left this up in the air (I left with the impression that you were willing to take it on from [your comment](https://github.com/brigade/scss-lint/issues/435#issuecomment-95292196)).

Feel free to submit a pull request!

**Comment by teoljungberg** [comment]
Great, I'll get back to you with a PR @sds

**Comment by lencioni** [comment]
@teoljungberg just checking in on the PR for this--have you made any progress?

**Comment by teoljungberg** [comment]
@lencioni I dropped the ball on actually making the PR. I opted to modify our code to take a `Tempfile` instead of a string. Which was resolved for our usecase in https://github.com/thoughtbot/hound-scss/pull/17 .

If anyone wants to take up my slack here, feel free to do so.
