### ISSUE TITLE
Allow linter plugins to be loaded from third-party repositories

### ISSUE THREAD

**Issue by sds** [brigade/scss-lint#440]
See discussion in #439 for the context that prompted this. This will build on #161 to allow `scss-lint` to support a diverse collection of linters without having to directly support them in the mainline code. Interested parties can create their own plugins and developers can choose to extend `scss-lint` with those plugins if desired.

**Comment by lencioni** [comment]
When considering how to architect the plugin system, it is probably worth looking at ESLint for inspiration: https://github.com/eslint/eslint

**Comment by sds** [comment]
Experimental support for loading custom linters via gems was implemented in #459. Please check out the `master` branch to take it for a spin. Feedback would be appreciated!
