### ISSUE TITLE
Allowing placeholders to follow a different convention

### ISSUE THREAD

**Issue by AurelioDeRosa** [brigade/scss-lint#451]
Hi.
I was setting up the configuration file for my team and I stumbled upon a use case that it's not possible to address with the linter.

I want to force the team to use a camel case convention to name mixins, functions, and variables. So, the convention is to write:

```scss
@mixin respondTo($minWidth, $maxWidth: "")
{
   // Do stuff
}
```

I also want the team to use hyphenated BEM to name selectors. BEM allows multiple words to be separated by a hyphen and sometimes you want to create a placeholder with the same name. For example, I might have:

```scss
%float-left,
.float-left
{
   float: left;
}
```

However, if I use the placeholder defined in this snippet as shown below:

```scss
.my-class
{
   @extend %float-left;
}
```

the linter will return an error. This happens because the placeholder is not camel case. According to the rules defined I'd have:

```scss
%floatLeft,
.float-left
{
   float: left;
}
```

which would be weird in my opinion.

So, I'd like to propose to add an option to treat placeholders differently from mixins, functions, and variables.

**Comment by sds** [comment]
Hey @AurelioDeRosa, thanks for suggesting ways we can improve `scss-lint`.

This makes sense to me. A pull request would be most welcome!

**Comment by AurelioDeRosa** [comment]
Hi @sds, I hadn't the time to submit a PR but I might have found a temporary solution. Specifically, you can avoid the tool to raise the error by setting `placeholder_convention: hyphenated_lowercase` for `NameFormat` and `placeholder_convention: hyphenated_BEM` for `SelectorFormat`.

What do you think of this approach?

**Comment by AurelioDeRosa** [comment]
I've just realized that there is no need to set `placeholder_convention: hyphenated_BEM` for `SelectorFormat` if it's the default. So, now I wonder if this issue is still valid since setting `placeholder_convention: hyphenated_lowercase` for `NameFormat` fixes the problem.

**Comment by sds** [comment]
Looking back at this, I don't think I understand this issue/request. However, since you have found a way to work around the problem, I believe that suggests there is nothing necessary on our side.

Feel free to submit a pull request if you feel differently. Thanks!
