### ISSUE TITLE
Linters not included in .scss-lint.yml seem to be running

### ISSUE THREAD

**Issue by FStop** [brigade/scss-lint#454]
I'm noticing something that's confusing after upgrading from 0.30.0 to 0.38.0, not sure if it's expected or not:

The project I'm working on has a .scss-lint.yml file where not all of the default linters are declared, for example there is nothing  for `ColorVariable`. By that I mean it's not set to false, there's just no mention of that linter at all.

There were no errors for `ColorVariable` before, but after upgrading to version `0.38.0` I'm getting a ton of `ColorVariable` errors and other linters that are not present in the repo's .scss-lint.yml.

Is it expected that default linters that are not declared in the repo's .scss-lint.yml will run anyway?

**Comment by sds** [comment]
Hi @FStop,

Sorry for the confusion; it looks like a recent edit to the README left out the fact that _all_ configurations extend the default configuration, so even if you don't explicitly list a linter in your repo's `.scss-lint.yml` file it will still be run if it is enabled in the default repo.

I've updated the README to better explain this in e7947ce0342c69db4790d74b2196c1da3a264257.

**Comment by FStop** [comment]
Thanks for the response. I made sure all of the default linters were declared and everything is working well.
