### ISSUE TITLE
Properties should be ordered display, height, margin, width?

### ISSUE THREAD

**Issue by corysimmons** [brigade/scss-lint#463]
Why is this? Could someone point me to some article about this?

Also, where are these recommendations defined in scss-lint?

**Comment by iamdarrenhall** [comment]
Check the [PropertySortOrder linter documentation](https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md#propertysortorder) for details and explanations, but it defaults to alphabetic sorting, and [sorting results in better GZIP compression](http://peteschuster.com/2014/12/reduce-file-size-css-sorting/) compared to no sorting.

**Comment by corysimmons** [comment]
Very cool. Thanks for the quick reply.
