### ISSUE TITLE
List of supported severities

### ISSUE THREAD

**Issue by damianszczepanik** [brigade/scss-lint#473]
I'm going to integrate this linter with another tool named [Sputnik](https://github.com/TouK/sputnik) and for this I parse JSON output.

Can you provide list of available severities and (if possible) how configure them in config file?

**Comment by sds** [comment]
Hey @damianszczepanik,

Thanks for taking on the task of integrating `scss-lint` with Sputnik. If I'm understanding your question, the answer can be found in the [README](https://github.com/brigade/scss-lint#severities).

In a nutshell, all lints have a `severity` of `warning` by default, and you can configure them via the [`severity`](https://github.com/brigade/scss-lint#severities) option.
