### ISSUE TITLE
Version 0.39.0 on Rubygems.org

### ISSUE THREAD

**Issue by starryeyez024** [brigade/scss-lint#474]
The latest release on github, [0.39.0](https://github.com/brigade/scss-lint/releases/tag/v0.39.0)
is not listed on [Rubygems.org](https://rubygems.org/gems/scss-lint/versions) - any particular reason or will this be added soon? Thanks!

**Comment by sds** [comment]
Hey @starryeyez024,

We recently changed the name of the gem from `scss-lint` to `scss_lint` (i.e. changing from a dash to an underscore) to match [Rubygems naming conventions](http://guides.rubygems.org/name-your-gem/). You can find the latest version at https://rubygems.org/gems/scss_lint.

Sorry for the confusion!
