### ISSUE TITLE
Inconsistent NestingDepth in nested vs pure selectors

### ISSUE THREAD

**Issue by viveleroi** [brigade/scss-lint#476]
I have `NestingDepth` and `SelectorDepth` enabled and set to `3`. I was under the impression it also checked selector depth, not just code blocks that are physically nested (because the end result is the same).

The following nesting triggers the linter warnings:

    .panel {
        > header {
            .btn-clear {
                &:hover { }
            }
        }
    }

Yet the following does not:

    .panel > header .btn-clear {
        &:hover { }
    }

The compiled output of these two are the same.

**Comment by sds** [comment]
`NestingDepth` does what it says: checks the depth of nested blocks. There is an open issue to have it ignore any blocks which are just parent reference suffixes (see #384).

I think it's important that `NestingDepth` and `SelectorDepth` retain these separate behaviors. The behavior you are seeing here, while perhaps odd at first, makes sense to me given the goals of each linter. If you find it confusing, you can disable one or the other.
