### ISSUE TITLE
Bad link in docs

### ISSUE THREAD

**Issue by ryanmc2033** [brigade/scss-lint#483]
On this page
https://github.com/brigade/scss-lint/blob/v0.39.0/lib/scss_lint/linter/README.md#vendorprefix

you link to https://github.com/brigade/scss-lint/blob/v0.39.0/lib/scss_lint/linter/data/prefixed-identifiers but that page does not exist

the real page is https://github.com/brigade/scss-lint/tree/v0.39.0/data/prefixed-identifiers

**Comment by sds** [comment]
Thanks for the report, @ryanmc2033.

Fixed in 5b537a09eb6831fb1771c440db0dec5ea17e15e7.
