### ISSUE TITLE
Add require: false to README?

### ISSUE THREAD

**Issue by golmansax** [brigade/scss-lint#496]
I ran into the issue described here: https://github.com/mkhairi/materialize-sass/issues/34 and had to add `require: false` when I switched from `scss-lint` to the `scss_lint` gem in order to precompile assets.  Is it worth a mention in the README?

**Comment by sds** [comment]
Good idea, @golmansax. I've done this in d495bc66b45920023855e76c5b8e8a55b38d3633. Thanks!
