### ISSUE TITLE
Error when calling scss-lint

### ISSUE THREAD

**Issue by CamJN** [brigade/scss-lint#502]
```
$ scss-lint --format JSON app/assets/stylesheets/welcome.scss 
Invalid configuration: private method `load' called for Psych:Module
```

version 0.39.0

**Comment by sds** [comment]
Hey @CamJN,

Can you include the following information to aid in debugging this issue?

- `ruby --version`
- `sass --version`

Thanks!

**Comment by CamJN** [comment]
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
Sass 3.4.15 (Selective Steve)

**Comment by sds** [comment]
I'm not able to reproduce this issue locally. 

A quick search reveals this may be a problem with the version of Psych you have installed, or your RubyGems version. Please see https://github.com/bbatsov/rubocop/issues/1510 for more information (there's not really anything `scss-lint` can do to help you in this case).
