### ISSUE TITLE
Illegal Nesting SCSS Error when using scss_lint v0.39.0

### ISSUE THREAD

**Issue by meowsus** [brigade/scss-lint#503]
Today I attempted to bump from `scss-lint v0.38.0` (with the dash) to `scss_lint v0.39.0` (without the dash) to get a patch fix I had requested into my application.

It caused massive failures when running our rspec test suite.

I found some articles around the internet that might help:
* https://github.com/mkhairi/materialize-sass/issues/34
* https://github.com/rails/sass-rails/issues/307

All of the failures were very similar to this one:

```
     Failure/Error: Unable to find matching line from backtrace
     ActionView::Template::Error:
       Illegal nesting: Only properties may be nested beneath properties.
     # (sass):10
     ...
```

Reverting back down to `scss-lint v0.38.0` (again, with the dash) resolved the issue for me.

**Comment by sds** [comment]
Unfortunately there isn't a simple way for `scss-lint` to work around this. See d495bc66b45920023855e76c5b8e8a55b38d3633 for details.

Related to #496.

**Comment by meowsus** [comment]
I was just about to close this issue myself, since I just found that blurb. Thank you so much for your response.
