### ISSUE TITLE
Enforce .class notation

### ISSUE THREAD

**Issue by Janther** [brigade/scss-lint#506]
There should be a linter that alerts when `[class="foo"]`is used instead of `.foo`
```SCSS
[class="foo"] {
    ...
}
```
I've seen it in some places and don't think there is a difference.
```SCSS
.foo {
    ...
}
```

**Comment by sds** [comment]
They are indeed different, @Janther.

`[class="foo"]` will match elements with only the class `foo`. `.foo` will match elements where at least one of the classes is `foo`. For example:

**Matched by `.foo` and `[class="foo"]`**
```
<p class="foo">...</p> 
```

**Matched by `.foo` only**
```
<p class="foo bar">...</p> 
```

Hope that helps.

**Comment by fosterinteractive** [comment]
Also regex-like matching use cases....

````
[class="^foo"] {
    ...
}
````

will target..

.foo-bar
.foo-fum

**Comment by Janther** [comment]
Of course i didn't think of those use cases.
Thanks
