### ISSUE TITLE
Feature Request: Enforce sassdoc documentation

### ISSUE THREAD

**Issue by awolkers** [brigade/scss-lint#510]
Add a linter to check if http://sassdoc.com/ documentation is set.

**Comment by sds** [comment]
Hey @awolkers,

This sounds like it could be useful, but I see some difficulty in identifying when certain kinds of comments are required (e.g. do you always want the `@example` directive present in your comments, or only for `@function` definitions?). 

Documentation guidelines are extremely organization-specific, and so it's not clear to me where to start in enforcement. There are tools like [Inch CI](https://inch-ci.org/) which specialize in giving you feedback about the quality of your documentation (right now only for Ruby/JavaScript/Elixir, but I believe you can write plugins to extend upon it). It may make more sense to utilize a separate tool in this case.

If you could provide some concrete suggestions of the kinds of checks you would like to see (and how those checks could be configured) it would be helpful in getting a better sense of what's involved here.

**Comment by sds** [comment]
Closing due to lack of response.

For what it's worth, I really do think this kind of linting would be best handled by a separate tool. Serious implementers should consider writing a plugin for [Inch CI](https://inch-ci.org/).
