### ISSUE TITLE
Discussion: should unitless line-height be preferred?

### ISSUE THREAD

**Issue by deepfriedmind** [brigade/scss-lint#515]
See [this post](http://meyerweb.com/eric/thoughts/2006/02/08/unitless-line-heights/) by Eric Meyer. Should scss-lint incorporate a bias towards unitless line-height values? It makes sense to me and I would argue that united line-heights most likely would stem from lack of knowledge about the subject (e.g. why pixel values should be avoided and how the consequences of em- and unitless values differ).

**Comment by Anahkiasen** [comment]
:+1: I would love a linter to enforce unitless line heights

**Comment by srawlins** [comment]
PropertyUnits can enforce unitless line heights (see [here](https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md#propertyunits) for the exact example of line-height).

I guess the suggestion is to change the default config of PropertyUnits?

**Comment by Anahkiasen** [comment]
I didn't even know PropertyUnits could do that. That solves it for me personally

**Comment by deepfriedmind** [comment]
Didn't know about PropertyUnits either. That works fine. :thumbsup:
