### ISSUE TITLE
If a linter is disabled by default, this is not documented anywhere

### ISSUE THREAD

**Issue by srawlins** [brigade/scss-lint#518]
... except `config/default.yml`.

Should the disabled-by-default linters (like BemDepth) be noted in `lib/scss-lint/linter/README.md`?

**Comment by sds** [comment]
Sorry for the delay in response, @srawlins.

I like having a single location where default enabled/disabled configuration can be consulted. It eliminates the possibility of drift between the actual default configuration and the README.

At the same time it's rare for a linter to change from being disabled by default to enabled by default, so the opportunity for documentation to fall out of sync should be relatively low.

**Comment by srawlins** [comment]
Yeah, I'm thinking the opportunity to drift is pretty low.

I think I also just assumed that _all_ linters were enabled by default, since there is no mention that this is not the case. (The README's [Linters](https://github.com/brigade/scss-lint#linters) heading writes that scss-lint has "opinionated defaults", but that's it.)

(Except, of course, the [Compass linters](https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/compass/README.md); "They are disabled by default")

I'll open a PR adding a few lines to linters/README.md, and see if it makes it noisy.

**Comment by lencioni** [comment]
> I think I also just assumed that all linters were enabled by default

I think it would be a good idea to make this change at some point.
