### ISSUE TITLE
Add linter disallowing adjoining classes

### ISSUE THREAD

**Issue by verpixelt** [brigade/scss-lint#532]
While I was configuring scss-lint for our future projects I was wondering about the lack of a rule for (or better to say against) "adjoining classes". Is there a specific reason why there is no such rule? If not, would you consider implementing it?

**Comment by sds** [comment]
I haven't personally heard the term "adjoining classes" before, but I assume you are referring to implementing this: https://github.com/CSSLint/csslint/wiki/Disallow-adjoining-classes

Feel free to submit a pull request!

**Comment by sds** [comment]
Implemented in 948535e65b460019bbe215c995dc60f7fb39ea2b. I've opted for the name `ChainedClasses` as I think it is a more intuitive name (though have documented "adjoining classes" as an alternate name).
