### ISSUE TITLE
MergableSelector output can't handle multiline selectors

### ISSUE THREAD

**Issue by baileyparker** [brigade/scss-lint#545]
When running the latest `scss-lint`, I noticed that some of the `MergeableSelector` warnings were being truncated like so:

    web/assets/sass/base.scss:100 [W] MergeableSelector: Merge rule `.dialog,

The root cause of this truncation was because I was piping the output through `grep` to see all of the `MergableSelector` warnings and the selector on line 100 had multiple lines. Without piping through grep, I get:

    web/assets/sass/base.scss:100 [W] MergeableSelector: Merge rule `.dialog,
    .modal` with rule on line 70

However, it seems to me like the newlines in the selector add no semantic value and instead make it slightly harder to parse (that is with your eyes, not with code :smile:) the list of errors.

In a sea of warning messages, I find this easier to read:

    web/assets/sass/base.scss:100 [W] MergeableSelector: Merge rule `.dialog, .modal` with rule on line 70

Could newlines in the output be stripped so that warnings for multiline selectors appear on one line?

**Comment by sds** [comment]
Fixed by @554.
