### ISSUE TITLE
Disabling SingleLinePerSelector Just Delays It

### ISSUE THREAD

**Issue by baileyparker** [brigade/scss-lint#546]
I'm using Eric Meyer's CSS Reset by including it in a separate `_reset.scss` file like so:

    // scss-lint:disable SingleLinePerSelector

    html, body, div, span, applet, object, iframe,
    h1, h2, h3, h4, h5, h6, p, blockquote, pre,
    a, abbr, acronym, address, big, cite, code,
    del, dfn, em, img, ins, kbd, q, s, samp,
    small, strike, strong, sub, sup, tt, var,
    b, u, i, center,
    dl, dt, dd, ol, ul, li,
    fieldset, form, label, legend,
    table, caption, tbody, tfoot, thead, tr, th, td,
    article, aside, canvas, details, embed,
    figure, figcaption, footer, header, hgroup,
    menu, nav, output, ruby, section, summary,
    time, mark, audio, video {
        border: 0;
        font: inherit;
        font-size: 100%;
        margin: 0;
        padding: 0;
        vertical-align: baseline;
    }

    /* HTML5 display-role reset for older browsers */
    article, aside, details, figcaption, figure,
    footer, header, hgroup, menu, nav, section {
        display: block;
    }

    body {
        line-height: 1;
    }

    ol,
    ul {
        list-style: none;
    }

    blockquote,
    q {
        quotes: none;
    }

    blockquote:before,
    blockquote:after,
    q:before,
    q:after {
        content: '';
        content: none;
    }

    table {
        border-collapse: collapse;
        border-spacing: 0;
    }

I disabled the SingleLinePerSelector warning for this file. However, scss-lint still reports warnings if I lint this reset file:

    _reset.scss:59 [W] SingleLinePerSelector: Each selector in a comma sequence should be on its own line
    _reset.scss:60 [W] SingleLinePerSelector: Each selector in a comma sequence should be on its own line
    _reset.scss:61 [W] SingleLinePerSelector: Each selector in a comma sequence should be on its own line
    _reset.scss:62 [W] SingleLinePerSelector: Each selector in a comma sequence should be on its own line
    _reset.scss:63 [W] SingleLinePerSelector: Each selector in a comma sequence should be on its own line
    _reset.scss:65 [W] SingleLinePerSelector: Each selector in a comma sequence should be on its own line
    _reset.scss:66 [W] SingleLinePerSelector: Each selector in a comma sequence should be on its own line
    _reset.scss:67 [W] SingleLinePerSelector: Each selector in a comma sequence should be on its own line
    _reset.scss:68 [W] SingleLinePerSelector: Each selector in a comma sequence should be on its own line
    _reset.scss:70 [W] SingleLinePerSelector: Each selector in a comma sequence should be on its own line
    _reset.scss:71 [W] SingleLinePerSelector: Each selector in a comma sequence should be on its own line
    _reset.scss:72 [W] SingleLinePerSelector: Each selector in a comma sequence should be on its own line
    _reset.scss:73 [W] SingleLinePerSelector: Each selector in a comma sequence should be on its own line
    _reset.scss:75 [W] SingleLinePerSelector: Each selector in a comma sequence should be on its own line
    _reset.scss:76 [W] SingleLinePerSelector: Each selector in a comma sequence should be on its own line
    _reset.scss:77 [W] SingleLinePerSelector: Each selector in a comma sequence should be on its own line
    _reset.scss:78 [W] SingleLinePerSelector: Each selector in a comma sequence should be on its own line
    _reset.scss:79 [W] SingleLinePerSelector: Each selector in a comma sequence should be on its own line
    _reset.scss:81 [W] SingleLinePerSelector: Each selector in a comma sequence should be on its own line
    _reset.scss:82 [W] SingleLinePerSelector: Each selector in a comma sequence should be on its own line
    _reset.scss:83 [W] SingleLinePerSelector: Each selector in a comma sequence should be on its own line

Interestingly, the last line in the file is 56 so the line numbers that it's reporting don't even exist. Am I using the disable comment incorrectly, or is this a bug?

**Comment by sds** [comment]
Thanks for the report, @baileyparker!

Fixed in 34f62fea806d048c7b79a4af7fa1fc992067a9b6.
