### ISSUE TITLE
NestingDepth causes: undefined method members for nil:NilClass

### ISSUE THREAD

**Issue by baileyparker** [brigade/scss-lint#547]
When enabling the NestingDepth warning, I get a ruby error:

    SCSSLint::Linter::NestingDepth raised unexpected error linting file base.scss: 'undefined method `members' for nil:NilClass'
    ~/.rvm/gems/ruby-1.9.3-p362/gems/scss_lint-0.40.1/lib/scss_lint/linter/nesting_depth.rb:40:in `simple_selectors'
    ~/.rvm/gems/ruby-1.9.3-p362/gems/scss_lint-0.40.1/lib/scss_lint/linter/nesting_depth.rb:34:in `ignore_selectors?'
    ~/.rvm/gems/ruby-1.9.3-p362/gems/scss_lint-0.40.1/lib/scss_lint/linter/nesting_depth.rb:15:in `visit_rule'
    ~/.rvm/gems/ruby-1.9.3-p362/gems/sass-3.4.16/lib/sass/tree/visitors/base.rb:36:in `visit'
    ~/.rvm/gems/ruby-1.9.3-p362/gems/scss_lint-0.40.1/lib/scss_lint/linter.rb:131:in `visit'
    ~/.rvm/gems/ruby-1.9.3-p362/gems/scss_lint-0.40.1/lib/scss_lint/linter.rb:142:in `block in visit_children'
    ~/.rvm/gems/ruby-1.9.3-p362/gems/scss_lint-0.40.1/lib/scss_lint/linter.rb:140:in `each'
    ~/.rvm/gems/ruby-1.9.3-p362/gems/scss_lint-0.40.1/lib/scss_lint/linter.rb:140:in `visit_children'
    ~/.rvm/gems/ruby-1.9.3-p362/gems/sass-3.4.16/lib/sass/tree/visitors/base.rb:38:in `visit'
    ~/.rvm/gems/ruby-1.9.3-p362/gems/scss_lint-0.40.1/lib/scss_lint/linter.rb:131:in `visit'
    ~/.rvm/gems/ruby-1.9.3-p362/gems/scss_lint-0.40.1/lib/scss_lint/linter.rb:142:in `block in visit_children'
    ~/.rvm/gems/ruby-1.9.3-p362/gems/scss_lint-0.40.1/lib/scss_lint/linter.rb:140:in `each'
    ~/.rvm/gems/ruby-1.9.3-p362/gems/scss_lint-0.40.1/lib/scss_lint/linter.rb:140:in `visit_children'
    ~/.rvm/gems/ruby-1.9.3-p362/gems/sass-3.4.16/lib/sass/tree/visitors/base.rb:36:in `block in visit'
    ~/.rvm/gems/ruby-1.9.3-p362/gems/scss_lint-0.40.1/lib/scss_lint/linter/nesting_depth.rb:11:in `visit_root'
    ~/.rvm/gems/ruby-1.9.3-p362/gems/sass-3.4.16/lib/sass/tree/visitors/base.rb:36:in `visit'
    ~/.rvm/gems/ruby-1.9.3-p362/gems/scss_lint-0.40.1/lib/scss_lint/linter.rb:131:in `visit'
    ~/.rvm/gems/ruby-1.9.3-p362/gems/scss_lint-0.40.1/lib/scss_lint/linter.rb:25:in `run'
    ~/.rvm/gems/ruby-1.9.3-p362/gems/scss_lint-0.40.1/lib/scss_lint/runner.rb:48:in `run_linter'
    ~/.rvm/gems/ruby-1.9.3-p362/gems/scss_lint-0.40.1/lib/scss_lint/runner.rb:29:in `block in find_lints'
    ~/.rvm/gems/ruby-1.9.3-p362/gems/scss_lint-0.40.1/lib/scss_lint/runner.rb:27:in `each'
    ~/.rvm/gems/ruby-1.9.3-p362/gems/scss_lint-0.40.1/lib/scss_lint/runner.rb:27:in `find_lints'
    ~/.rvm/gems/ruby-1.9.3-p362/gems/scss_lint-0.40.1/lib/scss_lint/runner.rb:17:in `block in run'
    ~/.rvm/gems/ruby-1.9.3-p362/gems/scss_lint-0.40.1/lib/scss_lint/runner.rb:16:in `each'
    ~/.rvm/gems/ruby-1.9.3-p362/gems/scss_lint-0.40.1/lib/scss_lint/runner.rb:16:in `run'
    ~/.rvm/gems/ruby-1.9.3-p362/gems/scss_lint-0.40.1/lib/scss_lint/cli.rb:58:in `scan_for_lints'
    ~/.rvm/gems/ruby-1.9.3-p362/gems/scss_lint-0.40.1/lib/scss_lint/cli.rb:51:in `act_on_options'
    ~/.rvm/gems/ruby-1.9.3-p362/gems/scss_lint-0.40.1/lib/scss_lint/cli.rb:28:in `run'
    ~/.rvm/gems/ruby-1.9.3-p362/gems/scss_lint-0.40.1/bin/scss-lint:6:in `<top (required)>'
    ~/.rvm/gems/ruby-1.9.3-p362/bin/scss-lint:23:in `load'
    ~/.rvm/gems/ruby-1.9.3-p362/bin/scss-lint:23:in `<main>'

Version information:

- SCSS-Lint version: 0.40.1
- Sass version: 3.4.16
- Ruby version: 1.9.3

The `.scss-lint.yml` file enables just NestingDepth:

    linters:
      NestingDepth:
        enabled: true
        max_depth: 4
        ignore_parent_selectors: true

This error does not occur if NestingDepth is disabled.

**Comment by baileyparker** [comment]
As I just realized in the PR, this issue has already been fixed.

**Comment by lencioni** [comment]
Thanks for helping out though!
