### ISSUE TITLE
Linter Request: Discourage transition all

### ISSUE THREAD

**Issue by baileyparker** [brigade/scss-lint#556]
I think the sentiment (especially on teams) regarding `transition: all` is to avoid it in most cases: http://stackoverflow.com/questions/8947441/css3-transitions-is-transition-all-slower-than-transition-x

Not so much from a performance perspective, of course, but I think most will recognize how it is possible that `transition: all` will unintentionally affect properties it was never meant to.

That is why I propose adding a linter that warns against uses of `all` in the `transition` or `transition-property` properties. If there's enough interest and someone is willing to merge this in, I can make a PR for this.

**Comment by Anahkiasen** [comment]
:+1: I try to do this myself but one sometimes slip from me, would love a rule to enforce it.

**Comment by sds** [comment]
Implemented in #556.
