### ISSUE TITLE
scss-lint vert slow when processing large set of if/else statements

### ISSUE THREAD

**Issue by nickdunn** [brigade/scss-lint#562]
I'm using latest gem (0.40.1).

When linting a file containing the following my CPU spikes at 100% and the execution never ends until I kill it. If I reduce the number of ifs to about 15 then the script will complete. Adding in more seems to exponentially increase script execution time.

Are there any known issues surrounding many if statements?

    @mixin icon-ie7($name, $colour:null) {
      font-family: pwsicons;
      font-style: normal;
      font-weight: normal;

      @if $colour {
        color: brandcolour("#{$colour}");
      }

      @if $name == 'play' {
        word-spacing: -1px;
      } @else if $name == 'search' {
        word-spacing: -2px;
      } @else if $name == 'quote-open' {
        word-spacing: -3px;
      } @else if $name == 'quote-close' {
        word-spacing: -4px;
      } @else if $name == 'chevrons-right' {
        word-spacing: -5px;
      } @else if $name == 'chevron-up' {
        word-spacing: -6px;
      } @else if $name == 'chevron-down' {
        word-spacing: -7px;
      } @else if $name == 'chevron-left' {
        word-spacing: -8px;
      } @else if $name == 'chevron-right' {
        word-spacing: -9px;
      } @else if $name == 'vertical-arrows' {
        word-spacing: -10px;
      } @else if $name == 'horizontal-arrows' {
        word-spacing: -11px;
      } @else if $name == 'download' {
        word-spacing: -12px;
      } @else if $name == 'share' {
        word-spacing: -13px;
      } @else if $name == 'twitter' {
        word-spacing: -14px;
      } @else if $name == 'facebook' {
        word-spacing: -15px;
      } @else if $name == 'google' {
        word-spacing: -16px;
      } @else if $name == 'linkedin' {
        word-spacing: -17px;
      } @else if $name == 'burger' {
        word-spacing: -18px;
      } @else if $name == 'placeholder' {
        word-spacing: -19px;
      } @else if $name == 'phone' {
        word-spacing: -20px;
      } @else if $name == 'external' {
        word-spacing: -21px;
      } @else if $name == 'envelope' {
        word-spacing: -22px;
      } @else if $name == 'video' {
        word-spacing: -23px;
      } @else if $name == 'list' {
        word-spacing: -24px;
      } @else if $name == 'info' {
        word-spacing: -25px;
      } @else if $name == 'pause' {
        word-spacing: -26px;
      } @else if $name == 'skip-forward' {
        word-spacing: -27px;
      } @else if $name == 'skip-back' {
        word-spacing: -28px;
      } @else if $name == 'volume-mute' {
        word-spacing: -29px;
      } @else if $name == 'volume-play' {
        word-spacing: -30px;
      } @else if $name == 'volume-up' {
        word-spacing: -31px;
      } @else if $name == 'volume-down' {
        word-spacing: -32px;
      } @else if $name == 'closed-captions' {
        word-spacing: -33px;
      } @else if $name == 'tfr' {
        word-spacing: -34px;
      } @else if $name == 'tmp' {
        word-spacing: -35px;
      } @else if $name == 'cg' {
        word-spacing: -36px;
      } @else if $name == 'location-marker' {
        word-spacing: -37px;
      } @else if $name == 'location-bubble' {
        word-spacing: -38px;
      } @else if $name == 'tick' {
        word-spacing: -39px;
      } @else if $name == 'warning' {
        word-spacing: -40px;
      } @else if $name == 'new-window' {
        word-spacing: -41px;
      } @else if $name == 'new-window-important' {
        word-spacing: -41px !important;
      } @else if $name == 'expand' {
        word-spacing: -42px;
      } @else if $name == 'new-window-rtl' {
        word-spacing: -43px;
      } @else if $name == 'new-window-rtl-important' {
        word-spacing: -43px !important;
      } @else if $name == 'external-rtl' {
        word-spacing: -44px;
      } @else if $name == 'share-rtl' {
        word-spacing: -45px;
      } @else if $name == 'list-rtl' {
        word-spacing: -46px;
      } @else if $name == 'reference-guide' {
        word-spacing: -47px;
      } @else if $name == 'calculator' {
        word-spacing: -48px;
      } @else if $name == 'video-gbm' {
        word-spacing: -49px;
      } @else if $name == 'camera' {
        word-spacing: -50px;
      } @else if $name == 'articles' {
        word-spacing: -51px;
      } @else if $name == 'report' {
        word-spacing: -52px;
      } @else if $name == 'live-person' {
        word-spacing: -53px;
      } @else if $name == 'apply' {
        word-spacing: -54px;
      } @else if $name == 'internal-link' {
        word-spacing: -55px;
      } @else if $name == 'calculator' {
        word-spacing: -56px;
      } @else if $name == 'ways-to-bank' {
        word-spacing: -57px;
      } @else if $name == 'pensions' {
        word-spacing: -58px;
      } @else if $name == 'business-accounts' {
        word-spacing: -59px;
      } @else if $name == 'finance-and-borrowing' {
        word-spacing: -60px;
      } @else if $name == 'business-cards' {
        word-spacing: -61px;
      } @else if $name == 'insurance' {
        word-spacing: -62px;
      } @else if $name == 'import-and-export' {
        word-spacing: -63px;
      } @else if $name == 'payment' {
        word-spacing: -64px;
      } @else if $name == 'knowledge-center' {
        word-spacing: -65px;
      } @else if $name == 'rmb' {
        word-spacing: -66px;
      } @else if $name == 'foreign-exchange' {
        word-spacing: -67px;
      } @else if $name == 'resources-center' {
        word-spacing: -68px;
      } @else if $name == 'info-alt' {
        word-spacing: -69px;
      }
    }

If I terminate the execution early I get the following output:

    ➜  styleguide git:(develop) ✗ scss-lint -c ../.scss-lint.yml public/assets/PWS171/stylesheets/sass/_icon_font_character_map.css.scss
    ^C(eval):7:in `visit_method': Interrupt
      from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.17/lib/sass/tree/visitors/base.rb:35:in `visit'
      from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.17/lib/sass/tree/visitors/set_options.rb:15:in `visit'
      from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.17/lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
      from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.17/lib/sass/tree/visitors/base.rb:52:in `map'
      from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.17/lib/sass/tree/visitors/base.rb:52:in `visit_children'
      from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.17/lib/sass/tree/visitors/base.rb:36:in `block in visit'
      from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.17/lib/sass/tree/visitors/set_options.rb:61:in `visit_if'
      from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.17/lib/sass/tree/visitors/base.rb:36:in `visit'
      from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.17/lib/sass/tree/visitors/set_options.rb:15:in `visit'
      from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.17/lib/sass/tree/visitors/set_options.rb:60:in `visit_if'
      from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.17/lib/sass/tree/visitors/base.rb:36:in `visit'
      from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.17/lib/sass/tree/visitors/set_options.rb:15:in `visit'
      from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.17/lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
      from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.17/lib/sass/tree/visitors/base.rb:52:in `map'
      from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.17/lib/sass/tree/visitors/base.rb:52:in `visit_children'
      from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.17/lib/sass/tree/visitors/base.rb:36:in `block in visit'
      from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.17/lib/sass/tree/visitors/set_options.rb:61:in `visit_if'
      from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.17/lib/sass/tree/visitors/base.rb:36:in `visit'
      from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.17/lib/sass/tree/visitors/set_options.rb:15:in `visit'
      from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.17/lib/sass/tree/visitors/set_options.rb:60:in `visit_if'
      from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.17/lib/sass/tree/visitors/base.rb:36:in `visit'
      from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.17/lib/sass/tree/visitors/set_options.rb:15:in `visit'
      from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.17/lib/sass/tree/visitors/set_options.rb:60:in `visit_if'
      from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.17/lib/sass/tree/visitors/base.rb:36:in `visit'
      from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.17/lib/sass/tree/visitors/set_options.rb:15:in `visit'
      from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.17/lib/sass/tree/visitors/set_options.rb:60:in `visit_if'
      from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.17/lib/sass/tree/visitors/base.rb:36:in `visit'
      from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.17/lib/sass/tree/visitors/set_options.rb:15:in `visit'
      from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.17/lib/sass/tree/visitors/set_options.rb:60:in `visit_if'
      from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.17/lib/sass/tree/visitors/base.rb:36:in `visit'
      from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.17/lib/sass/tree/visitors/set_options.rb:15:in `visit'
      from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.17/lib/sass/tree/visitors/set_options.rb:60:in `visit_if'
      from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.17/lib/sass/tree/visitors/base.rb:36:in `visit'
      from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.17/lib/sass/tree/visitors/set_options.rb:15:in `visit'
      from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.17/lib/sass/tree/visitors/set_options.rb:60:in `visit_if'
      from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.17/lib/sass/tree/visitors/base.rb:36:in `visit'
      from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.17/lib/sass/tree/visitors/set_options.rb:15:in `visit'
      from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.17/lib/sass/tree/visitors/set_options.rb:60:in `visit_if'
      from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.17/lib/sass/tree/visitors/base.rb:36:in `visit'
      from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.17/lib/sass/tree/visitors/set_options.rb:15:in `visit'
      from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.17/lib/sass/tree/visitors/set_options.rb:60:in `visit_if'
      from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.17/lib/sass/tree/visitors/base.rb:36:in `visit'
      from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.17/lib/sass/tree/visitors/set_options.rb:15:in `visit'
      from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.17/lib/sass/tree/visitors/set_options.rb:60:in `visit_if'
      from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.17/lib/sass/tree/visitors/base.rb:36:in `visit'
      from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.17/lib/sass/tree/visitors/set_options.rb:15:in `visit'
      from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.17/lib/sass/tree/visitors/set_options.rb:60:in `visit_if'
      from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.17/lib/sass/tree/visitors/base.rb:36:in `visit'
      from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.17/lib/sass/tree/visitors/set_options.rb:15:in `visit'
      from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.17/lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
      from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.17/lib/sass/tree/visitors/base.rb:52:in `map'
      from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.17/lib/sass/tree/visitors/base.rb:52:in `visit_children'
      from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.17/lib/sass/tree/visitors/base.rb:36:in `block in visit'
      from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.17/lib/sass/tree/visitors/set_options.rb:61:in `visit_if'
      from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.17/lib/sass/tree/visitors/base.rb:36:in `visit'
      from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.17/lib/sass/tree/visitors/set_options.rb:15:in `visit'
      from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.17/lib/sass/tree/visitors/set_options.rb:60:in `visit_if'
      from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.17/lib/sass/tree/visitors/base.rb:36:in `visit'
      from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.17/lib/sass/tree/visitors/set_options.rb:15:in `visit'
      from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.17/lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
      from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.17/lib/sass/tree/visitors/base.rb:52:in `map'
      from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.17/lib/sass/tree/visitors/base.rb:52:in `visit_children'
      from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.17/lib/sass/tree/visitors/base.rb:36:in `block in visit'
      from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.17/lib/sass/tree/visitors/set_options.rb:61:in `visit_if'
      from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.17/lib/sass/tree/visitors/base.rb:36:in `visit'
      from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.17/lib/sass/tree/visitors/set_options.rb:15:in `visit'
      from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.17/lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
      from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.17/lib/sass/tree/visitors/base.rb:52:in `map'
      from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.17/lib/sass/tree/visitors/base.rb:52:in `visit_children'
      from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.17/lib/sass/tree/visitors/base.rb:36:in `block in visit'

**Comment by srawlins** [comment]
Fascinating.

I took your input, and ran scss-lint through ruby-prof. [Gist](https://gist.github.com/srawlins/20e76f891fef6156fea5)

| `@if`s | Total time | `#extract_command` method calls | `#extract_command` total |
|----------|----------|----------|----------|
| 7         | 9.8 s     | 50_000   | 0.43 s |
| 8         | 20.3 s   | 99_000   | 0.93 s |
| 9         | 54.8 s   | 197_000 | 1.63 s |
| 10       | 169.5 s |394_000 | 3.90 s |

Looks like use of ControlCommentProcessor is doubling with each additional `@if` statement.

**Comment by sds** [comment]
Fixed in #579.

**Comment by nickdunn** [comment]
Thank you all :-)
