### ISSUE TITLE
css `image_url` bug

### ISSUE THREAD

**Issue by samirchian** [brigade/scss-lint#567]
![image](https://cloud.githubusercontent.com/assets/7979308/9526301/666ab63e-4c9d-11e5-8719-18d059a3456d.png)

**Comment by sds** [comment]
Hey @samirchian,

This error is legitimate. `image_url` can be written as `image-url` (with a hyphen), since `_` and `-` are treated the same in Sass.

If you disagree with the lint warning, you should disable it.
