### ISSUE TITLE
scss-lint doesn't like umlauts in file path

### ISSUE THREAD

**Issue by thykka** [brigade/scss-lint#591]
scss-lint was throwing this error within atom:

> TypeError: "\xCC" from ASCII-8BIT to UTF-8  /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/json/common.rb:286:in encode' /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/json/common.rb:286:ingenerate' /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/json/common.rb:286:in pretty_generate' /Library/Ruby/Gems/2.0.0/gems/scss-lint-0.38.0/lib/scss_lint/reporter/json_reporter.rb:13:inreport_lints' /Library/Ruby/Gems/2.0.0/gems/scss-lint-0.38.0/lib/scss_lint/cli.rb:142:in block in report_lints' /Library/Ruby/Gems/2.0.0/gems/scss-lint-0.38.0/lib/scss_lint/cli.rb:141:ineach' /Library/Ruby/Gems/2.0.0/gems/scss-lint-0.38.0/lib/scss_lint/cli.rb:141:in report_lints' /Library/Ruby/Gems/2.0.0/gems/scss-lint-0.38.0/lib/scss_lint/cli.rb:55:inscan_for_lints' /Library/Ruby/Gems/2.0.0/gems/scss-lint-0.38.0/lib/scss_lint/cli.rb:48:in act_on_options' /Library/Ruby/Gems/2.0.0/gems/scss-lint-0.38.0/lib/scss_lint/cli.rb:27:inrun' /Library/Ruby/Gems/2.0.0/gems/scss-lint-0.38.0/bin/scss-lint:6:in <top (required)>' /usr/bin/scss-lint:23:inload' /usr/bin/scss-lint:23:in `

> ' Report this bug at https://github.com/brigade/scss-lint/issues
> TypeError: "\xCC" from ASCII-8BIT to UTF-8
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/json/common.rb:286:in `encode'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/json/common.rb:286:in `generate'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/json/common.rb:286:in `pretty_generate'
/Library/Ruby/Gems/2.0.0/gems/scss-lint-0.38.0/lib/scss_lint/reporter/json_reporter.rb:13:in `report_lints'
/Library/Ruby/Gems/2.0.0/gems/scss-lint-0.38.0/lib/scss_lint/cli.rb:142:in `block in report_lints'
/Library/Ruby/Gems/2.0.0/gems/scss-lint-0.38.0/lib/scss_lint/cli.rb:141:in `each'
/Library/Ruby/Gems/2.0.0/gems/scss-lint-0.38.0/lib/scss_lint/cli.rb:141:in `report_lints'
/Library/Ruby/Gems/2.0.0/gems/scss-lint-0.38.0/lib/scss_lint/cli.rb:55:in `scan_for_lints'
/Library/Ruby/Gems/2.0.0/gems/scss-lint-0.38.0/lib/scss_lint/cli.rb:48:in `act_on_options'
/Library/Ruby/Gems/2.0.0/gems/scss-lint-0.38.0/lib/scss_lint/cli.rb:27:in `run'
/Library/Ruby/Gems/2.0.0/gems/scss-lint-0.38.0/bin/scss-lint:6:in `<top (required)>'
/usr/bin/scss-lint:23:in `load'
/usr/bin/scss-lint:23:in `<main>'
Report this bug at https://github.com/brigade/scss-lint/issues
  at /Users/thykka/.atom/packages/linter-scss-lint/lib/init.coffee:46:21
  at process._tickCallback (node.js:367:9)

Turns out it was caused by umlauts (ä, ö) in the scss file's path. I renamed the folder and the error disappeared.

I ran a search for this, but couldn't find anything useful. Thought I'd post this here in case someone else has the same issue.

**Comment by trotzig** [comment]
This doesn't seem to be a bug in the scss-lint project. I tried to reproduce it with a simple test:

```bash
⨠ echo ".foo {}" > örnsköldsvik.scss
⨠ scss-lint örnsköldsvik.scss
örnsköldsvik.scss:1 [W] EmptyRule: Empty rule
```

Are you using the `linter-scss-lint` (https://atom.io/packages/linter-scss-lint) plugin for Atom? This might be a bug in that project. If so, I suggest you file the issue there and see what they say.

By the way, yay for ömläåuts!
