### ISSUE TITLE
Feature Request: Colons for pseudo-classes and pseudo-elements

### ISSUE THREAD

**Issue by tysongach** [brigade/scss-lint#592]
CSS3 introduces a distinction between using single or double colons for pseudo-classes and pseudo-elements. Per [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-elements#Notes):

> Sometimes you will see double colons (::) instead of just one (:). This is part of CSS3 and an attempt to distinguish between pseudo-classes and pseudo-elements. Most browsers support both values.

It’d be nice to have a linter to check that:

- Pseudo-**classes** have **one** colon (`:`)
- Pseudo-**elements** have **two** colons (`::`)

**Comment by Anahkiasen** [comment]
:+1: would love that
