### ISSUE TITLE
Temp files created during linting are problematic for globbed watchers

### ISSUE THREAD

**Issue by SpenceDiNicolantonio** [brigade/scss-lint#595]
When files are linted, temp files are created in the same directory, with the same extension. This is problematic for globbed file watchers (e.g `gulp.watch`), which can end up triggering when these temp files are created/deleted. These temp files should probably be created within the system's temp directory.

See juanfran/gulp-scss-lint#36 for more info.

**Comment by sds** [comment]
Hey @SpenceDiNicolantonio,

`scss-lint` does not create temporary files as part of a lint run. Notice that in the issue you reference the files have the substring `scsslint` in their name&mdash;if you `grep` the `scss-lint` codebase for `scsslint`, you will not find it anywhere.

Thus a downstream tool is creating the temporary file, not `scss-lint`. Hope this helps.

**Comment by SpenceDiNicolantonio** [comment]
It looks like the temp files were created by the scss linter in WebStorm.

**Comment by AndyOGo** [comment]
I use PHPStorm, but I have the same issue with the newest version.
It's horrible it creates those tmp files inside source dir, and `scsslint` for js files does not make any sense...

`tasks/docs-scripts_scsslint_tmp1537225672253761620.js`
`tasks/scripts-bundle_scsslint_tmp4377624646903046346.js`

**Comment by AndyOGo** [comment]
I created an issue at the scss-lint inteliJ plugin
https://github.com/idok/scss-lint-plugin/issues/45
