### ISSUE TITLE
TrailingSemicolon with !default, !important

### ISSUE THREAD

**Issue by mrowles** [brigade/scss-lint#602]
I am getting errors with my SCSS where it thinks that there is no semicolon if I have a `!important` flag after the value.

    Case 1:
    $a-var-height: 100 !important; // warning here
    $b-var-height: 100px !important; // warning here
    
    Case 2:
    $b-var-height: 100;
    .b-var {
        height: em($b-var-height) !important; // warning here
    }

    Case 3:
    $c-var-height: 100px;
    .c-var-height {
        height: $c-var-height !important; // warning here
    }

So as you can see, I have covered all bases to ensure that at least somewhere I'd be writing the correct code. I have the rule in my .scss-lint.yml to allow for important rules:

    ImportantRule:
        enabled: true

My versions are:

* Sass 3.4.18
* SCSS Lint 0.42.0
* Ruby 2.0.0p481

Any help would be appreciated.

**Comment by mlarcher** [comment]
I just stumbled on the same issue, it seems the TrailingSemicolon rule doesn't account for this case.

**Comment by samuelmartineau** [comment]
:+1: 

Same there with **!global;**

Sass 3.4.18
SCSS Lint 0.42.0
Ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux

**Comment by lencioni** [comment]
Thanks for the report. I wasn't able to reproduce this problem with the cases you specified, but I was able to reproduce a problem when using `!default` and `!global` flags on variable declarations. I will push a fix for that shortly.

I may be mistaken, but I believe that `ImportantRule` will warn on any uses of `!important`. If you want to use `!important` then you should disable this rule. What output are you seeing when running scss-lint on the repro cases you posted?

**Comment by XhmikosR** [comment]
Hi, @lencioni. See https://travis-ci.org/twbs/bootstrap/builds/82182873

**Comment by lencioni** [comment]
@XhmikosR thanks for the link! It would be helpful to be able to see the source that it is breaking on here, however, I'm having a hard time finding the .scss files that are reported there (`scss/_variables.scss` and `scss/bootstrap-grid.scss`). Can you point me in the right direction?

**Comment by XhmikosR** [comment]
@lencioni: it's in our v4-dev branch; that's where we switched to Sass. Or check the branch I pushed the scss lint update, it's based on the same one.

**Comment by lencioni** [comment]
@XhmikosR great, thanks! I'm pretty sure that the fix I just pushed will fix this problem for you.

**Comment by XhmikosR** [comment]
Thanks! I'll try it as soon as there's a new gem out.

**Comment by sds** [comment]
Fixed by #605. Thanks for the report!

**Comment by XhmikosR** [comment]
Thanks! Confirmed https://travis-ci.org/twbs/bootstrap/builds/82208500.
