### ISSUE TITLE
`scss-lint:disable VendorPrefixes` issue

### ISSUE THREAD

**Issue by ArmorDarks** [brigade/scss-lint#616]
`// scss-lint:disable VendorPrefixes` doesn't work for placeholders and keyframes

Following

``` scss
// scss-lint:disable VendorPrefixes

@mixin ekzo-vendor($property, $value...) { // can be replaced with regular selector, like `.vendor1` — nothing will change
	-webkit-#{$property}: $value;
	   -moz-#{$property}: $value;
	    -ms-#{$property}: $value;
	     -o-#{$property}: $value;
	        #{$property}: $value;
}

@mixin ekzo-placeholder() { // can be replaced with regular selector, like `.vendor2` — nothing will change

	::-webkit-input-placeholder { @content }
			  :-moz-placeholder { @content }
			 ::-moz-placeholder { @content }
		 :-ms-input-placeholder { @content }

}

@mixin ekzo-keyframe($animation-name) { // can be replaced with regular selector, like `.vendor3` — nothing will change

	@-webkit-keyframes #{$animation-name} { @content; }

	@-moz-keyframes #{$animation-name}    { @content; }

	@-ms-keyframes #{$animation-name}     { @content; }

	@-o-keyframes #{$animation-name}      { @content; }

	@keyframes #{$animation-name}         { @content; }

}
```

will throw:

```
  14: [W] VendorPrefix:  Avoid vendor prefixes.
  15: [W] VendorPrefix:  Avoid vendor prefixes.
  22: [W] VendorPrefix:  Avoid vendor prefixes.
  24: [W] VendorPrefix:  Avoid vendor prefixes.
  26: [W] VendorPrefix:  Avoid vendor prefixes.
  28: [W] VendorPrefix:  Avoid vendor prefixes.
```

Note that regular vendor prefixes was skipped as expected

Issue

**Comment by JohnAlbin** [comment]
You mis-typed the name of the linter.

Change `// scss-lint:disable VendorPrefixes` to: `// scss-lint:disable VendorPrefix`

**Comment by ArmorDarks** [comment]
Ouch, my bad!

Thanks a lot for figuring it out. I was ensured that I've checked out name of linter and it was correct.

I probably was confused by the fact, that it ignored `-webkit-#{$property}: $value;` and so on, but now I realize that SCSS Lint just can't check selector name if it contains interpolation. Though, I wonder — is it correct behavior?

Anyway, thanks a lot once again!

**Comment by sds** [comment]
Hey @ArmorDarks,

`scss-lint` can't check the selector name if it contains interpolation because it can't know what the resulting output of the interpolation would be without additional processing. Sure there are perhaps some special cases, but the vast majority require explicit evaluation, and thus are not achievable through static analysis.
