### ISSUE TITLE
Custom linter not loading

### ISSUE THREAD

**Issue by lokesh** [brigade/scss-lint#620]
I'm running ```scss-lint``` with ```gulp + gulp-scss-lint``` and unable to load custom linters. The built in linters are working fine. I've posted my current configuration below. Any ideas?

Thanks ahead of time for all the hard work on this project!

```
$scss-lint --version
scss-lint 0.42.2
$ gulp --version
[16:26:11] CLI version 3.9.0
[16:26:11] Local version 3.9.0
```

```js
// gulpfile.js
gulp.task('scss-lint', function() {
  gulp.src(config.sass)
    .pipe(scsslint({
    	'maxBuffer': 1024 * 800,
    	'config': 'scss-lint.yml'
    }));
});
```

```ruby
# scss-lint.yml

scss_files: "**/*.scss"
plugin_directories: ['.scss-linters']

# List of gem names to load custom linters from (make sure they are already
# installed)

linters:
  AnotherLinter:
    enabled: true
...
```

```ruby
# .scss-linters/another_linter.rb

module SCSSLint
  class Linter::AnotherLinter < Linter
   include LinterRegistry

    def visit_id(id)
      add_lint(id, 'Just another linter!')
    end
  end
end
```

**Comment by cih** [comment]
Hey @lokesh,

I can't spot anything from your example that looks wrong, I'm also having problems replicating this. I've created a test case here https://github.com/cih/custom_linter_test, if I run `scss-lint` from the root of this I see the expected output including that provided by the custom linter. Would you mind seeing if you could either update this example or provide one that fails with more details?

Thanks!

**Comment by sds** [comment]
Closing due to lack of response. Feel free to reopen with a reproducible test case (ideally a repository that can be cloned and tested against). Thanks!

**Comment by lokesh** [comment]
@cih 
cc: @sds 

The test case @cih posted works locally. Also, I am unable to recreate my original issue locally any more. I spent some trying to isolate and recreate w/o any luck.

Sign this one off as most likely a user error. Sorry for the interrupt.

Thanks again for investigating and keep up the great work! :+1:
