### ISSUE TITLE
scss_lint throwing character has '-' without escape error

### ISSUE THREAD

**Issue by nim23** [brigade/scss-lint#637]
Versions:

Ruby -  2.2.3p173
scss-lint - 0.42.2

![screen shot 2015-11-02 at 3 48 28 pm](https://cloud.githubusercontent.com/assets/1999331/10886359/9f63d248-8179-11e5-8c75-0796bf44abc7.png)

above is the error I get on atom with linter-scss-lint, but is the same error that get's thrown when using scss-lint directly from the command line.

**Comment by srawlins** [comment]
You've got to help us out, @nim23: what is the scss content that led to this error?

**Comment by nim23** [comment]
@srawlins, sorry should have been more explicit

    .bag-page {
        display: block;
     }

Any class name's with `-` in them throws the warning.

**Comment by sds** [comment]
Hey @nim23,

What's the ASCII code of that character from the original file you're trying to lint? When I copy/paste that code as written in GitHub, I can't reproduce this issue.

My hunch is that the character is not a dash but an [en dash or em dash](https://en.wikipedia.org/wiki/Dash#En_dash_versus_em_dash), which is why you are seeing the error.

**Comment by nim23** [comment]
it's definitely not en dash or em dash, something seems off to me about my config/settings, I have grunt scss-lint which eventually run's this `scss-lint -c /Users/ngurung/.scsslint.yml /app/_small.scss` command but running the same command via command line seems to throw an error.

**Comment by nim23** [comment]
Apparently it's not the css it's something to do with `/usr/local/lib/ruby/gems/2.2.0/gems/scss_lint-0.42.2/lib/scss_lint/linter/selector_format.rb:79: warning: character class has '-' without escape: /^[_a-z0-9\/-a-z0-9]+$/` . Not a ruby expert but seems like a ruby warning, for that specific file on line 79.

**Comment by nim23** [comment]
Finally found the culprit. On my .scsslint.yml file I had an regex '^[_a-z0-9/-a-z0-9]+$' which was invalid and unescaped. Fixed it by changing the regex to ^[_a-z0-9\/\-a-z0-9]+$' . Closing the issue, thanks for replying to my queries.
