### ISSUE TITLE
PseudoElement regression

### ISSUE THREAD

**Issue by XhmikosR** [brigade/scss-lint#639]
The new check seems to wrongfully complain about the following

* `::-ms-expand`
*  `::placeholder`
* `::-webkit-progress-bar`
* `::-webkit-progress-value`
* `::-moz-progress-bar`

There might be more; these are the ones I noticed in our v4-dev Bootstrap branch.

Moved from https://github.com/brigade/scss-lint/pull/634#issuecomment-158989402

/CC @srawlins

**Comment by srawlins** [comment]
I'm on it. More comprehensive PR soon.

**Comment by lencioni** [comment]
Oh funny I hadn't noticed this issue but just submitted https://github.com/brigade/scss-lint/pull/640

I'll update mine to include some webkit and moz things.

**Comment by srawlins** [comment]
Oops thanks @lencioni . One more site that I found that included those is Caniuse: http://caniuse.com/#search=pseudo-element

**Comment by lencioni** [comment]
On that site I am noticing stuff like this:

> `:-ms-input-placeholder` for IE. 
> `::-ms-input-placeholder` for Edge (also supports webkit prefix)

which probably means that we need a list of things that can be either `:` or `::`.

**Comment by lencioni** [comment]
Or perhaps things that should be both `:` and `::`?

**Comment by srawlins** [comment]
@lencioni hmm. I think that the `:` _and_ `::` features are essentially relics. A tiny window where browsers were still sorting out what a pseudo-element is. I don't think its worth it to add support for "both" syntaxes.

That being said, IE 11 still has significant market share, so its presumably relevant for the next many months... *shrugs*

**Comment by sds** [comment]
@lencioni whoops, merged your commit before seeing your comment.

**Comment by XhmikosR** [comment]
Do you plan to make a new patch release with this fix?

**Comment by alexbuijs** [comment]
I've got ::-webkit-input-placeholder and:
  ::-webkit-scrollbar
  ::-webkit-scrollbar-button
  ::-webkit-scrollbar-track
  ::-webkit-scrollbar-track-piece
  ::-webkit-scrollbar-thumb
  ::-webkit-scrollbar-corner
  ::-webkit-resizer

**Comment by lencioni** [comment]
Thanks @alexbuijs! I added those in ddc23702f0259.

**Comment by lencioni** [comment]
@XhmikosR Yes, I think we will likely cut a patch release soon.

**Comment by lencioni** [comment]
And I found a bunch more to add. 8e0122645c0

**Comment by JohnAlbin** [comment]
I'm getting this error on -moz properties. Specifically, scss-lint is complaining about `button::-moz-focus-inner` in this way:

>  PseudoElement: Begin pseudo classes with a single colon: `:`

But I'm pretty sure that Mozilla browsers only recognize the double colon version of that selector.

For pseudo-elements and pseudo-classes defined in CSS2.1, all current browsers must support both single colon (:) and double colon(::) syntaxes. For pseudo-elements defined in later CSS specs, the single colon (:) version is _invalid_.

Also, note that IE8 (and other old browsers that don't understand the newer :: syntax) will see the double colon pseudo-elements and ignore the entire ruleset as per the requirements in the CSS 2.1 spec says to do.

Here's a list of -moz prefixes: https://developer.mozilla.org/en-US/docs/Web/CSS/Mozilla_Extensions
