### ISSUE TITLE
scss_files option not working properly?

### ISSUE THREAD

**Issue by sblask** [brigade/scss-lint#647]
I've got a Node project with a `.scss-lint.yml` that looks like this:

    scss_files: 'src/app/**/**/*.s+(a|c)ss'
    exclude:
        - 'dist/*'
        - 'node_modules/*'
        - 'something else'

I'd expect that only files whose path match the one given in `scss_files` will be linted. However, I have to have the `dist` and `node_modules` entries in the `exclude` as otherwise scss files in there are also linted, which slows everything down and gives a lot of unwanted output. I don't think this is expected behaviour, or am I doing something wrong?

**Comment by sds** [comment]
Hey @sblask,

To properly exclude all items under a directory, you need to use the `**/*` pattern, e.g.

```yaml
exclude:
  - 'dist/**/*'
  - 'node_modules/**/*'
```

Regarding the behavior of `scss_files`: how are you invoking `scss-lint`? If you specify a file, then the `scss_files` option is ignored and that file is used instead. Thus running `scss-lint .` will ignore the `scss_files` option, which could explain why your `dist` and `node_modules` directories are getting linted.

**Comment by sblask** [comment]
Thanks for the help! I was running `scss-lint .` because when I ran `scss-lint` I got `No SCSS files matched by the patterns:` (but no pattern was printed to screen, so not a big help figuring out the problem). I found the solution now, this: `*.s+(a|c)ss` did not work (we are moving from sass-lint to scss-lint and there it did work). I am not even sure it should work, but as all our files are `*.scss` anyway, I changed `scss_files` to `src/app/**/**/*.scss` and now I can run `scss-lint` and everything gets linted.

**Comment by sds** [comment]
Hey @sblask,

The reason the previous pattern didn't work (now that you mention it) is because `(a|c)` is not the way to do alternation with file glob patterns (though that is the way to do it with regexes). Thus if you had written `{a,c}` you would have had a working pattern.

Having said that, `scss-lint` doesn't support Sass anyway, so you wouldn't want to be linting your `.sass` files.
