### ISSUE TITLE
Add "scss-lint:disable-line"

### ISSUE THREAD

**Issue by callumlocke** [brigade/scss-lint#649]
Disabling a rule for a single line is a bigger deal than it should be:

```scss
@import 'food';

// scss-lint:disable ImportPath
@import 'normalize-scss/_normalize.scss';
// scss-lint:enable ImportPath

body {
```

ESLint [has a nicer way of doing it](http://eslint.org/docs/user-guide/configuring), which I think scss-lint should steal:

```scss
@import 'food';
@import 'normalize-scss/_normalize.scss'; // scss-lint:disable-line ImportPath

body {
```

**Comment by sds** [comment]
Hey @callumlocke,

You can already disable a single line by using a trailing comment.

```
@import 'normalize-scss/_normalize.scss'; // scss-lint:disable ImportPath
```

**Comment by bbugh** [comment]
The README doesn't specify the single line format, and I found this via a web search.

**Comment by BenLeggiero** [comment]
@bbugh Fixed! 😄
