### ISSUE TITLE
Supporting CSS Modules selector composition

### ISSUE THREAD

**Issue by CookPete** [brigade/scss-lint#652]
Apologies if this has already been discussed. I have searched but found no mention of it.

CSS Modules introduces [selector composition](https://github.com/css-modules/css-modules#composition) and with tools like webpack, it is possible to use both SASS and CSS modules for inline styles. The only issue is that `composes` is obviously not a legit property, and so `PropertySpelling` errors pop up.

I guess my questions are:

* Is it possible to ignore `composes` specifically, instead of disabling that rule completely?
* Is there a case for adding `composes` to the list of supported properties?

**Comment by sds** [comment]
You can add `composes` to the list of [`extra_properties`](https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md#propertyspelling) configuration for the `PropertySpelling` linter.
