### ISSUE TITLE
Can I use scss-lint in webpack? If can,how?

### ISSUE THREAD

**Issue by youngwind** [brigade/scss-lint#666]
I want to use a lint for scss in webpack and find this repo.
Can I use it in webpack?
If can,how?
I can not find the answer in the documentation.

**Comment by karlhorky** [comment]
There is a webpack loader called [scss-lint-loader](https://github.com/elijahmanor/scss-lint-loader) ([setup instructions here](https://github.com/karlhorky/scss-lint-loader/tree/patch-1#scss-lint-loader)), but `scss-lint` is pretty slow.

A much faster alternative that is more viable with webpack is the [sasslint-loader](https://github.com/alleyinteractive/sasslint-loader), which is based off of the node package [sass-lint](https://github.com/sasstools/sass-lint). `sass-lint` unfortunately doesn't have all features that `scss-lint` does.

**Comment by youngwind** [comment]
@karlhorky  Yes!  I know sass-lint. What's more, here's what the author says.
>Note This loader is under development and does not yet provide line numbers for errors and warnings in SCSS/SASS source files.

So I have not use it.
Finally, I take a compromise, using [gulp-scss-lint](https://www.npmjs.com/package/gulp-scss-lint/) instead, and found it not bad.

**Comment by karlhorky** [comment]
Yeah, I'm not sure why that's in the readme. It reports line numbers just fine for me :)

**Comment by KevinHerklotz** [comment]
Try this one: https://github.com/alleyinteractive/sasslint-webpack-plugin
That's the only one that works for me.

**Comment by karlhorky** [comment]
For new projects it looks like [stylelint](https://github.com/stylelint/stylelint) (with [stylelint-webpack-plugin](https://github.com/vieron/stylelint-webpack-plugin)) is a nice, extensible solution.
