### ISSUE TITLE
Column numbers

### ISSUE THREAD

**Issue by bignimbus** [brigade/scss-lint#670]
Scss-lint outputs the line number of the warning, but the column number would be helpful as well.  One edge case that happens to apply to me is using vim syntastic without a gutter.  With eslint and rubocop, column names are supported so syntastic is able to highlight the error/warning in the code itself.  This is not an option with scss-lint and may be considered a missing feature by some who prefer to see linter output in the code itself.  Examples:

### Eslint: error shows in gutter and on line/column
<img width="718" alt="screen shot 2016-01-08 at 1 09 58 pm" src="https://cloud.githubusercontent.com/assets/3976692/12206903/3fd1f4c6-b609-11e5-9c55-c0fd5fa24a3e.png">

#### but I don't like the gutter :(
<img width="719" alt="screen shot 2016-01-08 at 1 10 32 pm" src="https://cloud.githubusercontent.com/assets/3976692/12206907/41c90044-b609-11e5-87d3-2d1137f91877.png">

Context: here's the debug output of scss-lint via vim syntastic:

```
"test.scss" 4L, 36C
syntastic: 0.094294: &shell = '/bin/bash', &shellcmdflag = '-c', &shellpipe = '2>&1| tee
', &shellquote = '', &shellredir = '>%s 2>&1', &shellslash = 0, &shelltemp = 1, &shellxq
uote = '', &shellxescape = ''
syntastic: 0.094689: UpdateErrors (auto): default checkers
syntastic: 0.094967: CacheErrors: default checkers
syntastic: 0.095541: g:syntastic_aggregate_errors = 0
syntastic: 0.095701: getcwd() = '/Users/jeffreyauriemma/personal/game-of-life-n'
syntastic: 0.617293: CacheErrors: Invoking checker: scss/scss_lint
syntastic: 0.617819: SyntasticMake: called with options: {'errorformat': '%f:%l [%t] %m'
, 'makeprg': 'scss-lint test.scss', 'returns': [0, 1, 2, 65, 66]}
syntastic: 0.975939: checker output: ['test.scss:2 [W] PropertySpelling: Unknown propert
y silly-error', '']
syntastic: 0.976459: raw loclist: [{'lnum': 2, 'bufnr': 1, 'col': 0, 'valid': 1, 'vcol':
 0, 'nr': -1, 'type': 'W', 'pattern': '', 'text': 'PropertySpelling: Unknown property si
lly-error'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type':
'', 'pattern': '', 'text': ''}]
syntastic: 0.976817: getLocList: checker scss/scss_lint returned 1
syntastic: 0.976966: scss/scss_lint raw: [{'lnum': 2, 'bufnr': 1, 'col': 0, 'valid': 1,
'vcol': 0, 'nr': -1, 'type': 'W', 'pattern': '', 'subtype': 'Style', 'text': 'PropertySp
elling: Unknown property silly-error'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'v
col': 0, 'nr': -1, 'type': '', 'pattern': '', 'subtype': 'Style', 'text': ''}]
syntastic: 0.977243: quiet_messages filter: {}
syntastic: 0.977782: aggregated: {'_sorted': 0, '_name': 'scss_lint (scss)', '_owner': 1
, '_columns': 1, '_rawLoclist': [{'lnum': 2, 'bufnr': 1, 'col': 0, 'valid': 1, 'vcol': 0
, 'nr': -1, 'type': 'W', 'pattern': '', 'subtype': 'Style', 'text': 'PropertySpelling: U
nknown property silly-error'}]}
```

Since column data is being collected, I wonder if this could be solved by simply formatting the output differently.  I realize this may be a syntastic issue and not an scss-lint one, so any context would be helpful.

Any thoughts on this?  Thanks so much for a wonderful tool!

**Comment by abea** [comment]
I'm thinking it's more of a Syntastic issue. Using the scss-linter in Atom I do get the column as well as the line.

**Comment by bignimbus** [comment]
@abea thanks - opened https://github.com/scrooloose/syntastic/issues/1660 in syntastic in case any other vim users see the same problem.

**Comment by lencioni** [comment]
I think the Atom plugin must use the JSON formatter, which includes the column information. The Default formatter, which the syntastic syntax checker uses, seems to not include the column number. Probably the best thing to do would be to include the column number in the Default formatter, and then [update the syntastic checker to expect that format](https://github.com/scrooloose/syntastic/blob/dac07db61758590c71d655ed5403181af4e845a2/syntax_checkers/scss/scss_lint.vim#L30).

@sds what do you think?

**Comment by sds** [comment]
Syntastic added support for reading the JSON output of `scss-lint` in https://github.com/scrooloose/syntastic/commit/2db6f539d081baac7570186a96e7d9621893156c, so this is no longer a problem.
