### ISSUE TITLE
Aborted due to warnings without SCSS-Files

### ISSUE THREAD

**Issue by stephanfriedrich** [brigade/scss-lint#677]
Hi, thx for your great tool.
i use kickstart to create an initial project structure (1).
Is this behaviour expected ?

**Arror desription:**
on initial process there are no scss-files within these path.
**if i run scsslint, it Aborted due to warnings.**

    Running "scsslint:scss" (scsslint) task
    Running scss-lint on scss

    node_modules/grunt-scss-lint/test/fixtures/fail.scss
      2: [W] PropertySortOrder:  Properties should be ordered color, display
      3: [W] ColorKeyword:  Color `black` should be written in hexadecimal form as `#000000`
      3: [W] ColorVariable:  Color literals like `black` should only be used in variable declarations; they should be referred to via variable everywhere else.
      4: [W] FinalNewline:  Files should end with a trailing newline

    node_modules/grunt-scss-lint/test/fixtures/fail2.scss
      2: [W] Indentation:  Line should be indented with spaces, not tabs
      2: [W] SpaceAfterPropertyColon:  Colon after property should be followed by one space
      2: [W] ColorKeyword:  Color `red` should be written in hexadecimal form as `#ff0000`
      2: [W] ColorVariable:  Color literals like `red` should only be used in variable declarations; they should be referred to via variable everywhere else.
      3: [W] DeclarationOrder:  Expected item on line 3 to appear before line 2. Rule sets should be ordered as follows
      3: [W] Indentation:  Line should be indented with spaces, not tabs

**Expection:**
Imho it shouldn't validate scss if there are no scss files.

**gruntfile config:**
- grunt-scss-lint@0.3.8 
- scss_lint (0.43.2,)

The gruntfile scss-lint config looks like:

    scsslint: {
      options: {
        bundleExec: true,
        colorizeOutput: true,
        compact: true,
        config: '.scsslintrc',
        reporterOutput: null
      },
      scss: [
        'components/app/**/*.scss',
      ]
    }

have d nice day ;)

[1: generator-kickstart] (http://github.com/OpenSourceWorkflow/generator-kickstart)

**Comment by sds** [comment]
Hey @stephanfriedrich,

You need to exclude your `node_modules` directory. By default `scss-lint` will lint every `.scss` file under the current directory, recursively searching subdirectories. 

You can do this by adding the following to your `.scss-lint.yml`:

```yaml
exclude:
  - 'node_modules/**'
```

Hope that helps!

**Comment by stephanfriedrich** [comment]
oh nice thx
