### ISSUE TITLE
does not find custom plugins

### ISSUE THREAD

**Issue by smnbbrv** [brigade/scss-lint#683]
Hello guys,

I have a problem: the custom plugins folder .scss_linters is located in the folder where I run the scripts. For me it works fine, but for my colleagues all the custom plugins are just skipped. There is no error message that the plugins are missing and there are no errors although there must be, because as I told I have them on my computer.

The configuration file is the same as default file provided in your config folder. 

Could you, please, tell at least where to search for the errors / problems?

**Comment by abea** [comment]
This sounds like it might be related to your editor plugin as opposed to the scss-lint gem itself. I've made that mistake before. Does that sound right?

**Comment by smnbbrv** [comment]
I'm not sure I understand you right, but I run scss-lint from a command line, and a plugin is not an editor (IDE) plugin but a custom linter.

**Comment by cih** [comment]
Hi @smnbbrv,

By default custom linters are loaded from `.scss-linters` in the root of your repository, this however is local to your machine, each machine you want to use the custom linters would need to have the directory and linters within. Although you could check the `.scss-linters` into your projects source control if you're looking for a more distributed solution I would recommend using the `plugin_gems` option which would allow you to publish your custom linters to a repository which your team can contribute to.

Thanks,

Chris

**Comment by smnbbrv** [comment]
Hi @cih,

I added the .scss-linters folder to the root of my frontend folder and shared it by a simple commit with other developers, so we have all the same code and the same .yml configuration. It is located exactly at the same place. We have the same Ruby version, same gem version. The only difference is that my OS is El Capitan and theirs is Yosemite (which should not be an issue, right?).

What could be different to a standard people's setup is our project structure. Our frontend folder is located in a sub-sub-...-folder of a git root repository. What I tried about it: in configuration I put a fallback path from a repo's root e.g.:

```yml
plugin_directories: ['first-subfolder/second/etc/.../.scss-linters', '.scss-linters']
```

but it still did not help to solve the problem. And on my machine it works even without plugin_directories in yml file.

The most annoying is that it works on my machine. The same code, the same files, the same location. Furthermore, they created another linter and it does not work at their computers but at mine their linter works fine. So it cannot be the git issue I guess.

I am really lost. I would be happy to debug it and give you more information but I don't see any ability to do that. Also I am far away from being a Ruby expert.

I don't understand why the tool doesn't throw errors when it can't find linters specified in the configuration.  If there were some I could at least share them here or try to understand what is going on. What it does instead it just silently swallows the fact that it does not find the linters modules which are explicitly given in the configuration, so they are assumed to be loaded. This could lead to the problems like not working linters on some machines (like in my case) which will lead to the fact that ones who has a properly working linter would fix the problems for others with linters skipped.

**Comment by smnbbrv** [comment]
Btw, all the standard linters are working fine on all machines, including changing the configuration. So, if I change standard linters' setup, my colleagues' linting is also affected by that. So the only problem is enabling custom linters.

**Comment by cih** [comment]
Could you provide a repo that demonstrates the problem? If so will be happy to dig a little deeper. What version of `scss-lint` is in the projects `Gemfile` and is that the same version used when running on your machine `scss-lint -version`?

**Comment by smnbbrv** [comment]
@cih it is a private repo, yes, but I will try to reproduce it on a public one and come back here as soon as I can. Thanks!

**Comment by smnbbrv** [comment]
OK, this is the repo where I can reproduce the issue: https://github.com/smnbbrv/sass-lint-problem

That's the test environments:

The one 'where it works' fine:
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
scss-lint 0.43.2
Sass 3.4.20 (Selective Steve)

Output:
- ordinary `scss-lint` in a project root folder:
test.scss:1 [W] IdSelector: Avoid using id selectors
test.scss:1 [W] MyLinter: MyLinter1 works!

- ordinary `scss-lint` in a `subfolder` folder:
test.scss:1 [W] IdSelector: Avoid using id selectors
test.scss:1 [W] MyLinter: MyLinter2 works!

The one 'where it does not work':
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
scss-lint 0.38.0
Sass 3.4.19 (Selective Steve)

- ordinary `scss-lint` in a project root folder:
test.scss:1 [W] IdSelector: Avoid using id selectors

- ordinary `scss-lint` in a `subfolder` folder:
test.scss:1 [W] IdSelector: Avoid using id selectors

Before the one 'where it works' had the same versions, so I don't really see a problem.

Thank you in advance.

**Comment by cih** [comment]
From the looks of it the problem is with the `scss-lint` version, the custom linters feature was not added until the [0.40.0 release]. If you upgrade from version `0.38.0` to > `0.40.0` then it should work as expected.

[0.40.0 release]: https://github.com/brigade/scss-lint/releases/tag/v0.40.0

**Comment by smnbbrv** [comment]
Thank you for the hint, I will definitely try tomorrow! Could you please also tell how to upgrade it? I know, this is a dumb question, but we already tried a couple of times and did not succeed... As I already told we aren't "Ruby" guys :)

**Comment by sds** [comment]
Hey @smnbbrv,

Make sure you install the `scss_lint` gem (with an underscore) and not the `scss-lint` gem. It was renamed in [0.38.0](https://github.com/brigade/scss-lint/releases/tag/v0.38.0) to use [proper Rubygems naming conventions](http://guides.rubygems.org/name-your-gem/).

```
gem install scss_lint
```

**Comment by smnbbrv** [comment]
Thank you guys, you are magicians :) Works like a charm!
