### ISSUE TITLE
Can UnnecessaryMantissa include exceptions?

### ISSUE THREAD

**Issue by srawlins** [brigade/scss-lint#685]
We'd like to allow values like `1.0` in certain places, like the alpha value in rgba(). What do you think?

**Comment by sds** [comment]
I think you could create some sort of function whitelist, but then specifying the level of granularity for things like argument order is another matter.

So in your case, you want to allow `rgba(x, x, x, 1.0)`, so specifically the 4th argument of the `rgba` function. But you don't want `rgba(x, x, x, some-func(y, z, 1.0))` to be allowed.

I guess I find the desire to enforce `1.0` in this case a bit silly personally, but I can understand where you're coming from here (emphasizing it's a float for consistency reasons). If you can come up with a configuration system for this concept, go for it.

**Comment by srawlins** [comment]
Good call. This would probably be too difficult to specify; too complicated.
