### ISSUE TITLE
file_finder_spec cannot be run on Windows

### ISSUE THREAD

**Issue by ThomasR** [brigade/scss-lint#692]
[file_finder_spec](https://github.com/brigade/scss-lint/blob/master/spec/scss_lint/file_finder_spec.rb) executes `touch` and `mkdir`, which does not work in Windows.

It would be nice to have a platform independent implementation :)

**Comment by sds** [comment]
Fixed in 68918c03d80c1d9b40e7c7fd36e7c4dc5ed5205d.

**Comment by ThomasR** [comment]
Awesome! All tests are passing now (on Win7).
