### ISSUE TITLE
FileFinder test fails randomly (Arrays of filenames not sorted)

### ISSUE THREAD

**Issue by ThomasR** [brigade/scss-lint#693]
When running file_finder_spec.rb, [this part](https://github.com/brigade/scss-lint/blob/724860096bfcd723c06453bbe64bd49605842279/spec/scss_lint/file_finder_spec.rb#L22-L30) may fail

      context 'and there are SCSS files under the current directory' do
        before do
          `touch blah.scss`
          `mkdir -p more`
          `touch more/more.scss`
        end

        it { should == ['blah.scss', 'more/more.scss'] }

with the error message

     Failure/Error: it { should == ['blah.scss', 'more/more.scss'] }

       expected: ["blah.scss", "more/more.scss"]
            got: ["more/more.scss", "blah.scss"] (using ==)

---

This is because [`Find.find`](http://ruby-doc.org/stdlib-1.9.3/libdoc/find/rdoc/Find.html#method-c-find) does not guarantee a certain order.

There are two possible solutions for this, modify the [test](https://github.com/brigade/scss-lint/blob/724860096bfcd723c06453bbe64bd49605842279/spec/scss_lint/file_finder_spec.rb#L11) or the  [implementation](https://github.com/brigade/scss-lint/blob/724860096bfcd723c06453bbe64bd49605842279/lib/scss_lint/file_finder.rb#L36-L51). Not sure which one is better.

In both cases, the easy fix consists in sorting the array of found items. Either

    subject { super().find(patterns).sort }

in [file_finder_spec.rb:11](https://github.com/brigade/scss-lint/blob/724860096bfcd723c06453bbe64bd49605842279/spec/scss_lint/file_finder_spec.rb#L11)

or

      files.uniq.sort

in [file_finder.rb:50](https://github.com/brigade/scss-lint/blob/724860096bfcd723c06453bbe64bd49605842279/lib/scss_lint/file_finder.rb#L50)

**Comment by sds** [comment]
I'm happy to have `FileFinder#find` return its files in a well-defined order.

Fixed in fe04ca9.
