### ISSUE TITLE
Sites using scss-lint, things people have written about scss-lint

### ISSUE THREAD

**Issue by lencioni** [brigade/scss-lint#696]
It would be nice to have a list like this compiled for this project. Perhaps this could be added to the readme.

Some inspiration:

- http://babeljs.io/users/
- http://eslint.org/ (under "Who's using ESLint?")
- https://github.com/rackt/react-router/issues/2412
- https://github.com/facebook/react/wiki/Sites-Using-React

**Comment by sds** [comment]
One potential source: https://libraries.io/rubygems/scss_lint/dependent-repositories
