### ISSUE TITLE
Add TAP reporter

### ISSUE THREAD

**Issue by lencioni** [brigade/scss-lint#698]
To provide better compatibility with more tools, it would be nice to add a TAP reporter to SCSS-Lint.

http://testanything.org/

**Comment by sds** [comment]
Certainly open to adding support, just curious where this is coming from (considering we haven't gotten this request before). Was there any particular tool that would benefit from this?

**Comment by lencioni** [comment]
I am working on an internal tool that knows how to read TAP output. But, any TAP consumer could use this. Here's a list: http://testanything.org/consumers.html

It looks like there's one available for Jenkins, for instance. https://wiki.jenkins-ci.org/display/JENKINS/TAP+Plugin
