### ISSUE TITLE
Road to 1.0.0

### ISSUE THREAD

**Issue by lencioni** [brigade/scss-lint#725]
I think it would be good to put out a 1.0.0 release soon. I added some of our open issues to the [1.0.0 milestone](https://github.com/brigade/scss-lint/milestones/1.0.0) which I think we should use to track all of the things that we want to get done before releasing 1.0.0. And, once we are done with them, we should release 1.0.0.

As a first pass, I just went through our open issues and pretty subjectively added a few, so don't take this as prescriptive. If you think something is in there and shouldn't be, please speak up. And, if you can think of anything that isn't in there but should be, please open an issue.

I think that if we work together, we can get a 1.0.0 release out soon, so let's do it!

**Comment by sds** [comment]
Thanks for initially spearheading this push for 1.0.0, @lencioni.

I'm closing this as the appropriate issues are now marked with this milestone (and we now have a logo thanks to you!)

**Comment by lencioni** [comment]
👍
