### ISSUE TITLE
rake task doesn't seem to honor config file or defaults

### ISSUE THREAD

**Issue by mockdeep** [brigade/scss-lint#726]
When I run `scss-lint` at the command line, it works as expected, but running `rake scss_lint` results in a lot of `.css` (not `.scss`) files in other directories such as `node_modules` and `coverage` being reported on. I tried adding a `scss_files` option to `.scss-lint.yml`, but this had no effect.

**Comment by svyatov** [comment]
Same for me, current workaround:

```
  SCSSLint::RakeTask.new do |task|
    task.files = [] # hack, otherwise scss_lint doesn't respect scss_files option in .scss-lint.yml
  end
```

**Comment by connorshea** [comment]
I've been having the same problem, now running into it on two different projects.

**Comment by connorshea** [comment]
[Here's the file with the Rake task](https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/rake_task.rb) and [the most recent commit](https://github.com/brigade/scss-lint/commit/5b2dbfd1b366e22f24af1afb9f6de8aa87940213) which seems to modify it.

**Comment by connorshea** [comment]
This is kind of a major pain point for me, any updates @sds?

**Comment by sds** [comment]
Happy to accept a pull request with a fix. We don't use the Rake integration at @brigade so it would be appreciated to get some outside help on this. Thanks!

**Comment by svyatov** [comment]
@sds I'm happy to provide PR, but this is not actually a bug as it turned out, so I need your help to implement a proper fix.

Method which causing this issue is `SCSSLint::FileFinder#find`:

```
    def find(patterns)
      # If no explicit patterns given, use patterns listed in config
      patterns = @config.scss_files if patterns.empty?

      matched_files = extract_files_from(patterns)
      if matched_files.empty?
        raise SCSSLint::Exceptions::NoFilesError,
              "No SCSS files matched by the patterns: #{patterns.join(' ')}"
      end

      matched_files.reject { |file| @config.excluded_file?(file) }
    end
````

This method is called in `SCSSLint::CLI#scan_for_lints` like so:

```
          FileFinder.new(config).find(options[:files]).map do |file_path|
            { path: file_path }
          end
```

RakeTake sets default files as `['.']`:

```
    # Create the task so it is accessible via +Rake::Task['scss_lint']+.
    def initialize(name = :scss_lint)
      @name = name
      @files = ['.'] # Search for everything under current directory by default
      @quiet = false

      yield self if block_given?

      define
    end
```

And this is what gets `find` method as `patterns` and then...

```
      patterns = @config.scss_files if patterns.empty?
```

So it has its pattern and ignores config scss_files option. We need to come to some conclusion about what gets precedence over what and just implement this logic. Or describe current state of things in README. Best option would be to do both, I think (fix it and document it).

As of now, looks like my [workaround](https://github.com/brigade/scss-lint/issues/726#issuecomment-189489967) above isn't so hacky after all.

**Comment by sds** [comment]
Sorry for the long delay in response, @svyatov.

I've gone ahead and changed the implementation to respect the `scss_files` option if no files are explicitly defined when initializing the Rake task.

Thus the task will now respect file preference in the following order (first one to specify file paths/patterns wins):
1. Files specified directly on the command line (e.g. via `rake scss_lint[file1 file2]`)
2. Files specified in Rake task initialization (e.g. `SCSSLint::RakeTask.new { |t| t.files = [...] }`)
3. Files specified in the global `scss_files` configuration option in `.scss-lint.yml`

Hope that helps!

**Comment by tagliala** [comment]
Hi,

I'm still having issues using scss_lint 0.50.3 with Rails 5.0.0.1 (and 4.2.7.1)

.scss-lint.yml
```yml
scss_files: 'app/assets/stylesheets/**/*.scss'

# ...
```

scss_lint.rake
```rb
# frozen_string_literal: true
if %w(development test).include? Rails.env
  require 'scss_lint/rake_task'

  SCSSLint::RakeTask.new do |t|
    # SCSSLint does not respect config file
    # Workaround for https://github.com/brigade/scss-lint/issues/726
    t.files = []
  end

  task(:default).prerequisites.unshift task(:scss_lint)
end
```

output:
```sh
$ rake scss_lint
app/assets/stylesheets/test.scss:2:3 [W] SpaceAfterPropertyName: Property name should be immediately followed by a colon

scss-lint found one or more lints
```

If I change the rake file to
```rb
# frozen_string_literal: true
if %w(development test).include? Rails.env
  require 'scss_lint/rake_task'

  task(:default).prerequisites.unshift task(:scss_lint)
end
```

here it is the output:
```bash
$ rake scss_lint
$
```

**Comment by sds** [comment]
Hey @tagliala,

Sorry this still doesn't seem to be working for you. Would really appreciate a pull request at this point, as I don't have the bandwidth to look into this myself. 

Thanks!

**Comment by tagliala** [comment]
@sds I was about to take a look but it doesn't seem an issue anymore 🤔
