### ISSUE TITLE
Nested element in element#id selector gives parse error.

### ISSUE THREAD

**Issue by vhaarr** [brigade/scss-lint#742]
Hi,

`section#prosjekter {
	article {

	}
}
`

Gives me an unexpected parse error: "Unexpected parse error in fileat line 1 col 1".
Removing the article block removes the parse error and shows the actual linter mistakes.

Using https://github.com/AtomLinter/linter-sass-lint 1.1.1 on atom 1.5.3 on linux.

**Comment by sds** [comment]
Hey @vhaarr,

linter-sass-lint does not use SCSS-Lint, as mentioned in its [documentation](https://github.com/AtomLinter/linter-sass-lint).

Please file your issue with the [sass-lint](https://github.com/sasstools/sass-lint) project.
