### ISSUE TITLE
couldn't find HOME environment -- expanding `~'

### ISSUE THREAD

**Issue by lencioni** [brigade/scss-lint#746]
I'm setting up scss-lint in a new environment and am running into this when I run `bundle exec scss-lint`.

```
couldn't find HOME environment -- expanding `~'
/tmp/d20160303-22941-rc8ll2/monorail-solano-ghe/vendor/bundle/ruby/1.9.1/gems/scss_lint-0.47.1/lib/scss_lint/config.rb:42:in `home'
/tmp/d20160303-22941-rc8ll2/monorail-solano-ghe/vendor/bundle/ruby/1.9.1/gems/scss_lint-0.47.1/lib/scss_lint/config.rb:42:in `user_file'
/tmp/d20160303-22941-rc8ll2/monorail-solano-ghe/vendor/bundle/ruby/1.9.1/gems/scss_lint-0.47.1/lib/scss_lint/config.rb:204:in `initialize'
/tmp/d20160303-22941-rc8ll2/monorail-solano-ghe/vendor/bundle/ruby/1.9.1/gems/scss_lint-0.47.1/lib/scss_lint/plugins/linter_dir.rb:9:in `new'
/tmp/d20160303-22941-rc8ll2/monorail-solano-ghe/vendor/bundle/ruby/1.9.1/gems/scss_lint-0.47.1/lib/scss_lint/plugins/linter_dir.rb:9:in `initialize'
/tmp/d20160303-22941-rc8ll2/monorail-solano-ghe/vendor/bundle/ruby/1.9.1/gems/scss_lint-0.47.1/lib/scss_lint/plugins.rb:29:in `new'
/tmp/d20160303-22941-rc8ll2/monorail-solano-ghe/vendor/bundle/ruby/1.9.1/gems/scss_lint-0.47.1/lib/scss_lint/plugins.rb:29:in `block in plugin_directories'
/tmp/d20160303-22941-rc8ll2/monorail-solano-ghe/vendor/bundle/ruby/1.9.1/gems/scss_lint-0.47.1/lib/scss_lint/plugins.rb:28:in `map'
/tmp/d20160303-22941-rc8ll2/monorail-solano-ghe/vendor/bundle/ruby/1.9.1/gems/scss_lint-0.47.1/lib/scss_lint/plugins.rb:28:in `plugin_directories'
/tmp/d20160303-22941-rc8ll2/monorail-solano-ghe/vendor/bundle/ruby/1.9.1/gems/scss_lint-0.47.1/lib/scss_lint/plugins.rb:18:in `all'
/tmp/d20160303-22941-rc8ll2/monorail-solano-ghe/vendor/bundle/ruby/1.9.1/gems/scss_lint-0.47.1/lib/scss_lint/plugins.rb:12:in `load'
/tmp/d20160303-22941-rc8ll2/monorail-solano-ghe/vendor/bundle/ruby/1.9.1/gems/scss_lint-0.47.1/lib/scss_lint/config.rb:235:in `load_plugins'
/tmp/d20160303-22941-rc8ll2/monorail-solano-ghe/vendor/bundle/ruby/1.9.1/gems/scss_lint-0.47.1/lib/scss_lint/config.rb:28:in `load'
/tmp/d20160303-22941-rc8ll2/monorail-solano-ghe/vendor/bundle/ruby/1.9.1/gems/scss_lint-0.47.1/lib/scss_lint/config.rb:15:in `default'
/tmp/d20160303-22941-rc8ll2/monorail-solano-ghe/vendor/bundle/ruby/1.9.1/gems/scss_lint-0.47.1/lib/scss_lint/config.rb:31:in `load'
/tmp/d20160303-22941-rc8ll2/monorail-solano-ghe/vendor/bundle/ruby/1.9.1/gems/scss_lint-0.47.1/lib/scss_lint/cli.rb:139:in `setup_configuration'
/tmp/d20160303-22941-rc8ll2/monorail-solano-ghe/vendor/bundle/ruby/1.9.1/gems/scss_lint-0.47.1/lib/scss_lint/cli.rb:54:in `act_on_options'
/tmp/d20160303-22941-rc8ll2/monorail-solano-ghe/vendor/bundle/ruby/1.9.1/gems/scss_lint-0.47.1/lib/scss_lint/cli.rb:33:in `run'
/tmp/d20160303-22941-rc8ll2/monorail-solano-ghe/vendor/bundle/ruby/1.9.1/gems/scss_lint-0.47.1/bin/scss-lint:7:in `<top (required)>'
/tmp/d20160303-22941-rc8ll2/monorail-solano-ghe/vendor/bundle/ruby/1.9.1/bin/scss-lint:23:in `load'
/tmp/d20160303-22941-rc8ll2/monorail-solano-ghe/vendor/bundle/ruby/1.9.1/bin/scss-lint:23:in `<main>'
Report this bug at https://github.com/brigade/scss-lint/issues
To help fix this issue, please include:
- The above stack trace
- SCSS-Lint version: 0.47.1
- Sass version: 3.4.21
- Ruby version: 1.9.3
- Contents of /tmp/d20160303-22941-rc8ll2/monorail-solano-ghe/.scss-lint.yml
```

This is a CI environment where we are creating a tmp dir via `Dir.mktmpdir` to run things in. We take this path and later set the `HOME` environment variable to it by passing it to [`Open3.popen2e`](http://ruby-doc.org/stdlib-1.9.3/libdoc/open3/rdoc/Open3.html#method-c-popen2e) when we run `bundle exec scss-lint`, which is where we get this error. We also have other jobs in here that from what I can tell are set up in the same way to set this environment variable and then run a different `bundle exec` command (e.g. `rspec` and `rubocop`), but those don't blow up in this way. Any ideas on what is happening here?

For reference, this is the line that is blowing up (I believe on the call to `Dir.home`): https://github.com/brigade/scss-lint/blob/e6d20f537d021445da9583cbe1ec29bcded5ec32/lib/scss_lint/config.rb#L42

**Comment by sds** [comment]
The error could only be caused by your environment not having a `HOME` variable defined.

You can verify this by trying:

```
⨠ ruby -e "puts Dir.home"
/Users/shane
```

```
⨠ env -i ruby -e "puts Dir.home"
-e:1:in `home': couldn't find HOME environment -- expanding `~' (ArgumentError)
	from -e:1:in `<main>'
```

There's not much else I believe I can offer here–you'll need to dig into your CI environment to figure out what's going on.

**Comment by lencioni** [comment]
Yeah, I think you are right. I think I trace through the execution path more closely and see if I can find a missing link. Thanks!

**Comment by modkaffes** [comment]
@lencioni Did you ever find a solution to this issue? It's still plaguing my local env due to my lack of ruby experience.

**Comment by modkaffes** [comment]
@lencioni No problem, it was a really long shot posting in a thread this old. I'll try to find a solution myself, too. Thank you!

**Comment by modkaffes** [comment]
I'm putting this here for future self-reference in case this issue happens again, and of course for anyone that might have the same problem.

After much research regarding how Ruby detects User's home dir, I stumbled upon this comment:
https://github.com/AtomLinter/linter-rubocop/issues/168#issuecomment-254122274, which made me realize I also had some problematic zplug plugin in my `.zshrc`, namely `https://github.com/knu/z`
