### ISSUE TITLE
Rake 11

### ISSUE THREAD

**Issue by connorshea** [brigade/scss-lint#756]
scss-lint is locked to Rake 10, which in turn is causing rspec-rails to use 4.1.0. If there aren't any major issues, can the requirements be changed to allow [Rake 11](https://github.com/ruby/rake/blob/master/History.rdoc)?

**Comment by connorshea** [comment]
@lencioni done :)

**Comment by paulkogel** [comment]
thanks for fixing this. is there a chance to get a new gem release with this change included?

**Comment by sds** [comment]
Released in [0.48.0](https://github.com/brigade/scss-lint/releases/tag/v0.48.0)

**Comment by paulkogel** [comment]
thank you!
