### ISSUE TITLE
Port to Javascript possible?

### ISSUE THREAD

**Issue by juan-orca** [brigade/scss-lint#765]
Hi,

I'm not comfortable with the Ruby ecosystem. How hard would it be to port this to Javascript?

**Comment by lencioni** [comment]
It depends heavily on the Sass parser internals, which is Ruby, so it would be difficult. You might be interested in one of these projects:

- https://github.com/sasstools/sass-lint
- https://github.com/stylelint/stylelint

**Comment by juan-orca** [comment]
Very nice, thanks! Do you know the difference between either of the two

**Comment by lencioni** [comment]
I haven't worked with them before, but sass-lint is a linter for Sass and SCSS whereas stylelint is a linter for [PostCSS](https://github.com/postcss), which can be configured to look like SCSS or other things. If I was starting a new project today, I'd likely explore PostCSS first.
