### ISSUE TITLE
Defining custom "SelectorFormat"s for certain files

### ISSUE THREAD

**Issue by monoblaine** [brigade/scss-lint#770]
I use the [hyphenated_BEM](http://csswizardry.com/2013/01/mindbemding-getting-your-head-round-bem-syntax/) convention mostly, but occasionally need to use the `hyphenated_lowercase`, too. (To create custom button variants for Bootstrap, for instance)

If I'm not wrong, you can only define one `SelectorFormat`. At first I thought I should group the scss files that use different conventions in separate folders and create `.scss-lint.yml` files that only define the related `SelectorFormat` and put them into each folder, but then I realized scss-lint dropped support for merging configuration files. Creating a copy of the root `.scss-lint.yml` and just changing `SelectorFormat` seems to be the solution, but a cumbersome one.

So, is there any way to achive what I need?

**Comment by sds** [comment]
Hey @monoblaine, sorry for the delay in response.

You can achieve what you desire by writing a custom linter that inherits from `SelectorFormat`. 

```ruby
class MyCustomSelectorFormat < SCSSLint::Linter::SelectorFormat; end
```

You can then configure this linter to apply to a different set of files, using a different convention.

```yaml
linters:
  MyCustomSelectorFormat:
    include: custom/set/of/files/**/*.css
    convention: hyphenated_lowercase
```

Hope that helps.
