### ISSUE TITLE
Linter proposal : PseudoElement should allow option to force single colon

### ISSUE THREAD

**Issue by TheAddictedOne** [brigade/scss-lint#776]
Hi there !
Thanks for your amazing work on scss-lint !

This is a request to accept and force single-colon with a specific rule.
The reason is our old friend IE8 recognize only single-colon for pseudo-elements like `:after` and `:before`.
Doc' from MSDN here : https://msdn.microsoft.com/en-us/library/cc304078(v=vs.85).aspx

**Comment by mathieuhays** [comment]
Duplicates of #678
