### ISSUE TITLE
PropertySpelling: Not picking up `text-align: centre;`

### ISSUE THREAD

**Issue by s10wen** [brigade/scss-lint#778]
I noticed `text-align: centre;` in a `.scss` file, but it didn't get picked up. Wondering if it should have done?

**Comment by chris-dura** [comment]
The `PropertySpelling` linter would only pick up mistakes in the `property`, not the `value` of the property. So, if it was `text-algin: center`, the linter would pick it up.

There's a way to disallow certain `units` from being used in property values, but not sure there is currently a way to blacklist a misspelled (or alternative spelling) of a valid value.

**Comment by s10wen** [comment]
@chris-dura ah, thanks.

Closing in favour of https://github.com/brigade/scss-lint/issues/779
