### ISSUE TITLE
DisableLinterReason:true crashes when the comment is far from the rule

### ISSUE THREAD

**Issue by LuigiRamosWeb** [brigade/scss-lint#780]
This code makes scss-lint crash when config is set to DisableLinterReason:true
<pre>
// other comment
.my-rule {
	// scss-lint:disable ColorVariable
	background-color: #fff;
}
</pre>

Program output:

<pre>
SCSSLint::Linter::DisableLinterReason raised unexpected error linting file .\scss-lint-DisableLinterReason-test.scss: 'u
ndefined method `end_pos' for nil:NilClass'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/scss_lint-0.48.0/lib/scss_lint/linter/disable_linter_reason.rb:30:in `visit_command_
comment'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/scss_lint-0.48.0/lib/scss_lint/linter/disable_linter_reason.rb:11:in `visit_comment'

C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.15/lib/sass/tree/visitors/base.rb:36:in `visit'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/scss_lint-0.48.0/lib/scss_lint/linter.rb:138:in `visit'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/scss_lint-0.48.0/lib/scss_lint/linter.rb:149:in `block in visit_children'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/scss_lint-0.48.0/lib/scss_lint/linter.rb:147:in `each'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/scss_lint-0.48.0/lib/scss_lint/linter.rb:147:in `visit_children'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.15/lib/sass/tree/visitors/base.rb:38:in `visit'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/scss_lint-0.48.0/lib/scss_lint/linter.rb:138:in `visit'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/scss_lint-0.48.0/lib/scss_lint/linter.rb:149:in `block in visit_children'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/scss_lint-0.48.0/lib/scss_lint/linter.rb:147:in `each'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/scss_lint-0.48.0/lib/scss_lint/linter.rb:147:in `visit_children'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.15/lib/sass/tree/visitors/base.rb:38:in `visit'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/scss_lint-0.48.0/lib/scss_lint/linter.rb:138:in `visit'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/scss_lint-0.48.0/lib/scss_lint/linter.rb:41:in `run'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/scss_lint-0.48.0/lib/scss_lint/runner.rb:53:in `run_linter'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/scss_lint-0.48.0/lib/scss_lint/runner.rb:35:in `block in find_lints'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/scss_lint-0.48.0/lib/scss_lint/runner.rb:33:in `each'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/scss_lint-0.48.0/lib/scss_lint/runner.rb:33:in `find_lints'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/scss_lint-0.48.0/lib/scss_lint/runner.rb:19:in `block in run'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/scss_lint-0.48.0/lib/scss_lint/runner.rb:18:in `each'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/scss_lint-0.48.0/lib/scss_lint/runner.rb:18:in `run'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/scss_lint-0.48.0/lib/scss_lint/cli.rb:74:in `scan_for_lints'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/scss_lint-0.48.0/lib/scss_lint/cli.rb:59:in `act_on_options'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/scss_lint-0.48.0/lib/scss_lint/cli.rb:33:in `run'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/scss_lint-0.48.0/bin/scss-lint:7:in `<top (required)>'
C:/Ruby193/bin/scss-lint:23:in `load'
C:/Ruby193/bin/scss-lint:23:in `<main>'
Report this bug at https://github.com/brigade/scss-lint/issues
</pre>

**Comment by srawlins** [comment]
Sorry, it looks like DisableLinterReason probably does not work at all if you are using Sass pre-3.4.20 (December 2015) (you have 3.4.15). My [CommentNode fix](https://github.com/sass/sass/commit/d6ea4c61169dc45bb773a21a399c82c08b526aae) was released in 3.4.20.

scss-lint's [stated minimum sass version is 3.4.15](https://github.com/brigade/scss-lint/blob/master/scss_lint.gemspec#L29). Maybe we should bump this? I don't know how I didn't catch this before...

**Comment by sds** [comment]
Thanks for the clarification, @srawlins. 

I've bumped the minimum version in 786033e4f6504098d205c27d2e9268d3a0db13a3.

**Comment by LuigiRamosWeb** [comment]
You're right, it's working fine with Sass 3.4.20.
Thanks!!
