### ISSUE TITLE
Print to stdout total number of errors

### ISSUE THREAD

**Issue by mir4a** [brigade/scss-lint#784]
It would be nice to have a total number of errors/warnings after each run:
![screen shot 2016-04-26 at 22 24 13](https://cloud.githubusercontent.com/assets/618900/14831297/c4fcbdda-0bfd-11e6-9d70-467166130f42.png)

**Comment by mir4a** [comment]
Added PR #785

**Comment by srawlins** [comment]
Dup of https://github.com/brigade/scss-lint/issues/655 which has many comments

**Comment by sds** [comment]
Closing as duplicate.
