### ISSUE TITLE
How to make scss_files option accept multiple paths

### ISSUE THREAD

**Issue by hansspiess** [brigade/scss-lint#786]
I have a project structure where there is a core bundle (including scss ressources) which is required by project instances which also contain scss ressources. i want to include my .scss-lint.yml only in the core bundle but make the additional ressources in the requiring project inherit the settings from core.
is this possible?

**Comment by sds** [comment]
I'm not sure I understand your particular situation (it depends how you've organized your projects) but there is currently no way to extend the list of default `scss_files` specified in your configuration.

Is there any reason you can't just run `scss-lint` from the root of the project and have it automatically lint all SCSS files?
