### ISSUE TITLE
last_comment deprecation warning

### ISSUE THREAD

**Issue by joshminnie** [brigade/scss-lint#790]
I upgraded to the latest version of the scss_lint gem and now I'm receiving this deprecation warning:

```
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
```

It looks like this may be related to the version of rake that came in when I did the upgrade. My rake gem version went from 10.5.0 to 11.1.2.

See [rake/lib/rake/task_manager.rb](https://github.com/ruby/rake/blob/e4277364efa6c28afa3f502361d8446f0f0ccdef/lib/rake/task_manager.rb#L10)

**Comment by sds** [comment]
This is a warning from Rake which SCSS-Lint has no control over. We don't use `last_comment` anywhere in our codebase.

https://github.com/ruby/rake/issues/116
