### ISSUE TITLE
BorderZero

### ISSUE THREAD

**Issue by marcobiedermann** [brigade/scss-lint#791]
BorderZero should be always `false` because `border: 0;` is not equal `border: none;`

http://dabblet.com/gist/8716224

**Comment by chris-dura** [comment]
Isn't this like saying `background: blue;` is not equal to `background: no-repeat;`?
You're providing values to the shorthand that override completely different properties.

**Comment by sds** [comment]
Hey @marcobiedermann, thanks for raising this potential source of confusion.

It seems like the `BorderZero` linter is misleading. Specifying `none` is indeed semantically different than `0`: the former is specifying `border-style` while the latter is specifying `border-width`.

Perhaps there's a reconciliation here in that usually when developers specify `none` they _meant_ to use `0`?

@lencioni It looks like you originally added this linter in in 1fe3d5fa. Did you have any thoughts on this issue?

**Comment by abea** [comment]
An option could be added to use `none` instead of `0`. Then teams could maintain consistency but have the choice. The description could be expanded to something like ``border: 0;` is preferred over `border: none;`, otherwise user property `border-style``

**Comment by lencioni** [comment]
> @lencioni It looks like you originally added this linter in in 1fe3d5f. Did you have any thoughts on this issue?

No, I don't think it matters much either way. I think the `0` behavior is likely less surprising for developers, but what matters most is consistency.

**Comment by sds** [comment]
I've added some clarification to the documentation in d19d990. Thanks for your input!
