### ISSUE TITLE
Documentation for the SCSS-lint rules

### ISSUE THREAD

**Issue by varemenos** [brigade/scss-lint#798]
You guys need to consider creating a documentation website for the scss-lint rules like [eslint does](http://eslint.org/docs/rules/). I've searched everywhere and couldn't find neither a website neither any kind of file that would comprehensively explain what all the rules of scss-lint do.

**Comment by srawlins** [comment]
That is a very cool site.

Is anything in particular missing from the "Linters Documentation" link [here](https://github.com/brigade/scss-lint#linters)?

**Comment by varemenos** [comment]
Ohh, I guess I missed that link, thanks a lot.
Nothing is missing in the list but the link needs to draw more attention, it's something that should be advertised more (or be linked somewhere in the beginning of the page).

I also scanned the project's root for a directory that would be called `docs` or anything similar but didn't find anything, maybe you should consider giving higher priority to that too.

Should I leave this issue open?

**Comment by srawlins** [comment]
I agree, @varemenos, I wish it were one click to see the list of linters (i.e. in the top level README), rather than 2 clicks. Then again the top-level README is already really long and informative... not sure...

Let's leave the issue open for the maintainers to give an answer.

**Comment by lencioni** [comment]
I think people might also be looking for the word "rules" instead of "linters"--perhaps it would help if we changed the terminology used here?

**Comment by sds** [comment]
I believe I've addressed this in d88401f. Thanks for your feedback!
