### ISSUE TITLE
PseudoElement ignoring enable false in .scss-lint.yml

### ISSUE THREAD

**Issue by lstanard** [brigade/scss-lint#802]
I updated to v0.48.0 today and started getting the following warning: `[W] PseudoElement: Begin pseudo elements with double colons: '::'`.  I previously did not have any `PseudoElement` rule in my `.scss-lint.yml` config file. I added the PseudoElement rule and `enable: false`, but it continues to issue warnings. 

It does respect disabling in the source via `//scss-lint:disable PseudoElement`.

Commented on issue https://github.com/brigade/scss-lint/issues/678, moved here to a separate issue.

**Comment by srawlins** [comment]
Did you try <code>enable<strong>d</strong>: false</code>? https://github.com/brigade/scss-lint#configuration

**Comment by lstanard** [comment]
Good catch. Thanks @srawlins
