### ISSUE TITLE
PseudoElement linter throwing warning in v0.39.0?

### ISSUE THREAD

**Issue by meowsus** [brigade/scss-lint#804]
In my projects Gemfile I've had version `0.39.0` locked in for well over 6 months.

```
gem 'scss_lint', '0.39.0', require: false
```

A few weeks ago I started receiving PseudoElement linter warnings, specifically:

```
PseudoElement: Begin pseudo elements with double colons: `::`
```

It's my understanding that the `PseudoElement` linter was added in version `0.43.0`. I've checked and double checked the version but can't, for the life of me, understand why I'd just start getting these warnings if I hadn't manually bumped the version in my Gemfile.

Does anyone have any idea why this might be happening?

**Comment by sds** [comment]
You must be executing SCSS-Lint outside the Bundler context (i.e. without `bundle exec`). Barring something really strange with how your `PATH` has been configured, that's the likely explanation.

What does `gem list scss_lint` say? Do you see version 0.43.0 or newer in the list? That's likely how you're picking it up.

**Comment by meowsus** [comment]
Yeah, I have a bunch installed apparently. This is most likely SublimeLinter (which is what I use to run my linters in Sublime) running `scss-lint` and not `bundle exec scss-lint`.

```
$ scss-lint -v
0.48.0
$ bundle exec scss-lint -v
0.39.0
```

Thanks for your time and help.
