### ISSUE TITLE
Get the file that a variable was declared in

### ISSUE THREAD

**Issue by shukriadams** [brigade/scss-lint#808]
In a custom linter, given the method

        def visit_prop(node)
            if node.children.first.is_a?(Sass::Script::Tree::Variable) 
            end
        end

is it possible to get the filename that the variable node.children.first was declared in? 

Thanks.

**Comment by srawlins** [comment]
I don't think so. Though if you have a purpose in mind, I bet you could monkey-patch something in, or submit an issue at http://github.com/sass/sass...

**Comment by sds** [comment]
While this kind of information sharing wasn't considered when the `Linter` class was designed, you can currently get this information by accessing `engine.filename` from within your custom linter.

**Comment by shukriadams** [comment]
@sds engine.filename is returning the file the variable is being used in, not the declaring file. I managed to find the filename another way - not as clean but still acceptable, so I can live with this.

Really love this linter by the way, it's making my work life so much easier.

**Comment by sds** [comment]
Ah sorry, I misread your question. Yes you would need to submit a pull request to the upstream Sass project.

Glad you're finding the tool useful!
