### ISSUE TITLE
Shorthand counts !important as a value

### ISSUE THREAD

**Issue by ernestoalejo** [brigade/scss-lint#809]
When I set [Shorthand](https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md#shorthand) to `[1, 2, 4]` it thinks `!important` is a value:

```
_navbar.scss:38:18 [E] Shorthand: Shorthands of length `3` are not allowed. Value was `15px 20px !important`
```

The full line of the error is:

```scss
padding: 15px 20px !important;
```

**Comment by thomasfrobieter** [comment]
I got this error too. But i use the default configuration [1, 2, 3, 4].

> Shorthands of length `5` are not allowed. Value was `10px 60px 10px $grid !important`

**Comment by trcarden** [comment]
Ditto
