### ISSUE TITLE
Remove ColorKeyword linter

### ISSUE THREAD

**Issue by viridium** [brigade/scss-lint#817]
Back in the days when we used to code with punch cards, we dreamt of programming models that were friendlier to a human being. And then, when we started coding in assembler language, we kept dreaming on. Although we generally jostled around limping and making a mess of the dream, we still dreamt of it.

The point is this: symbols are important to human beings. We work with symbols as much as we can. For the ColorKeyword linter to come and tell us to stop using symbols for something as intimately known to us as a color is preposterous.

Please disable this linter by default or remove it altogether. I haven't heard this kind of an aberration in ages.

**Comment by lencioni** [comment]
The trouble with color keywords in real world applications is that there are not many of them, so they are unlikely to match up with how you want things to look most of the time. Given that you likely won't be using a color keyword for every color, this rule intends to enforce consistency in how colors are used in an application by forbidding color keywords altogether. This is particularly effective when used alongside the ColorVariable rule, which requires that all colors are variables and that hex colors are only used when being assigned to variables.

I think that there are people who find this rule useful, so I don't think it should be removed. As far as disabling it by default, I agree and believe that we should disable all rules by default (see #564).

**Comment by sds** [comment]
Hey @viridium,

I can appreciate that without context some checks seem ill-conceived or not useful.

I can assure you the logic behind `ColorKeyword` is sound. While @lencioni has already elaborated a bit on why this linter exists, please consult the [documentation](https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md#colorkeyword), specifically the closely-related linter `ColorVariable`.

Thanks!

**Comment by viridium** [comment]
Just so I understand, because I've read that bit (it was mentioned in the `ColorKeyword` documentation and it was right below, so it was tough to miss): is the variable specification designed such that it intrudes upon the color namespace? I should hope not, because otherwise how does it not intrude upon all the other keywords, like "bold", "none", "middle", and so on? I ask because, apparently, "color names look like variables".

Now, as far as consistency is concerned, I might ask in turn: why don't we just design SCSS so people only have to work with bits. Then we can translate those bits into CSS on the way out and get all the nasty higher level ugly-looking CSS code.

(Since the ColorVariable bit was brought up, how would you comment on the value of this linter for theme files?)
