### ISSUE TITLE
scss_files option ignored with new version 0.50.0

### ISSUE THREAD

**Issue by AllSpeeds** [brigade/scss-lint#831]
First noticed in CircleCI installing via:

`gem install scss_lint` which gave me the new version `0.50.0` with the change to `scss_lint` option.

https://github.com/brigade/scss-lint/releases/tag/v0.50.0

Receiving this error:
`No files, paths, or patterns were specified`

from `.scss-lint.yml` in root of project:
`scss_files: 'client/styles/'`

**Comment by sds** [comment]
Thanks for the report @AllSpeeds.

Fixed in e3a68d4 and released as a hotfix in [0.50.1](https://github.com/brigade/scss-lint/releases/tag/v0.50.1).
