### ISSUE TITLE
SpaceAfterComment default value

### ISSUE THREAD

**Issue by gtakat** [brigade/scss-lint#832]
Hi,

About SpaceAfterComment, default value defined `one_space` in document.
https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md#spaceaftercomment

But in program, default value is `at_least_one_space`.
https://github.com/brigade/scss-lint/blob/master/config/default.yml#L186

There is a possibility that the document or code is wrong.

**Comment by ivantsepp** [comment]
Hey! great catch. I accidentally left the `at_least_one_space` value while doing some testing locally. I just made a PR to correct the default configuration

**Comment by sds** [comment]
Thanks for the report! Fixed in #834 and released as 0.50.2
