### ISSUE TITLE
SpaceAfterComment fails linting with consecutive comments or indentation

### ISSUE THREAD

**Issue by huwdavidevans** [brigade/scss-lint#838]
This rule has started failing this second comment, despite having a space after the literal.

![screen shot 2016-09-09 at 09 16 05](https://cloud.githubusercontent.com/assets/2056794/18382228/fc35f278-7677-11e6-85ad-0454384ad83d.png)

But it passes if the indentation is removed, or there is a line break between the comments.

![screen shot 2016-09-09 at 09 17 36](https://cloud.githubusercontent.com/assets/2056794/18382262/1a7bb9c0-7678-11e6-9eb0-30b5ea8b090d.png)

![screen shot 2016-09-09 at 09 16 38](https://cloud.githubusercontent.com/assets/2056794/18382258/1656743e-7678-11e6-9a25-0dc4eaa03d3a.png)

Neither work around is acceptable, so I will disable the rule for now, but is this symptomatic of another rule? Are consecutive comments discouraged? Seems odd, especially as a linter ignore reason.

scss_lint (0.50.2)
ruby 2.2.1p85
OSX El Capitan

**Comment by huwdavidevans** [comment]
Quick work! Thanks.

**Comment by ivantsepp** [comment]
Thanks for the quick fix!
