### ISSUE TITLE
VariableForProperty does not consider !important rules

### ISSUE THREAD

**Issue by elgervb** [brigade/scss-lint#842]
Consider following sass:

$black: #000;

.selector {
    background-color: $black;
    color: $black !important;
}

The scss-linter gives use the following warning:
`warning  Property color should use a variable rather than a literal value  VariableForProperty
`
Looks like this is due to the !important rule.

Thanks for fixing ;-)

**Comment by abea** [comment]
I created a Sass file with only that code on the latest version and only get a warning about the !important flag. Is this code isolated when you get the warning?

**Comment by elgervb** [comment]
Ai, my bad! 

Just did a `scss-lint --v` and it turned out I have an older version...
scss-lint 0.38.0

After updating, all my problems are resolved ;-)
