### ISSUE TITLE
Possibility to disable setting Error Status Codes

### ISSUE THREAD

**Issue by danez** [brigade/scss-lint#846]
It would be nice for jenkins if we could disable scss_lint setting error codes > 0 when a linting error happens. 

As we are using checkstyle we do not want the jenkins job to fail if there are only linting errors but warn instead, which is done by the checkstyle plugin.

As a workaround we completely ignore the return status of scss_lint which is also not nice because in case there is a real error we won't notice it immediately.

**Comment by trotzig** [comment]
I might have misunderstood something here. But if you want to treat everything as warnings, why don't you set `severity` to `warning` on all lints?

**Comment by sds** [comment]
Closing due to lack of response.
