### ISSUE TITLE
PseudoElement linter is not working as expected

### ISSUE THREAD

**Issue by astronati** [brigade/scss-lint#850]
**The problem**
Updating version from 0.48.0 to 0.50.2 the `PsuedoElement` validator does not catch the error of the missing double comma.

**Comment by sds** [comment]
Hey @astronati,

I'm not sure what you mean by "missing double comma."

It would be really helpful if you provided some example code with the output you saw from SCSS-Lint and the output you expected. Thanks!

**Comment by sds** [comment]
Closing due to lack of response.
