### ISSUE TITLE
undefined method `visit_method' for Sass::Script::Tree::Operation:Class

### ISSUE THREAD

**Issue by ncino-cpezza** [brigade/scss-lint#872]
undefined method `visit_method' for Sass::Script::Tree::Operation:Class

Getting this error that i have tied back to this but have no reference to the scss-lint anymore on my computer. any ideas where to go?

**Comment by sds** [comment]
Hey @ncino-cpezza,

This code is from the `sass` gem. I'm not sure how you're hitting this situation if you've uninstalled SCSS-Lint from your system. 

I'm going to close this unless you can provide more information. Thanks!
