### ISSUE TITLE
Atom editor - linter-scss-lint gem error

### ISSUE THREAD

**Issue by Janyoungjae** [brigade/scss-lint#881]
I am having issue with [Linter-scss-lint] in Atom Editor. I tried Google searching the problem but still could not solve the issue.

this is Atom Editor error messages Ignoring bcrypt-3.1.9 because its extensions are not built. Try: gem pristine bcrypt --version 3.1.9 Ignoring bcrypt-ruby-3.0.1 because its extensions are not built. Try: gem pristine bcrypt-ruby --version 3.0.1 Ignoring binding_of_caller-0.7.2 because its extensions are not built. Try: gem pristine binding_of_caller --version 0.7.2 Ignoring bson-2.3.0 because its extensions are not built. Try: gem pristine bson --version 2.3.0 Ignoring byebug-3.5.1 because its extensions are not built. Try: gem pristine byebug --version 3.5.1 Ignoring debug_inspector-0.0.2 because its extensions are not built. Try: gem pristine debug_inspector --version 0.0.2 Ignoring eventmachine-1.0.4 because its extensions are not built. Try: gem pristine eventmachine --version 1.0.4 Ignoring executable-hooks-1.3.2 because its extensions are not built. Try: gem pristine executable-hooks --version 1.3.2 Ignoring ffi-1.9.14 because its extensions are not built. Try: gem pristine ffi --version 1.9.14 Ignoring ffi-1.9.6 because its extensions are not built. Try: gem pristine ffi --version 1.9.6 Ignoring gem-wrappers-1.2.7 because its extensions are not built. Try: gem pristine gem-wrappers --version 1.2.7 Ignoring hiredis-0.5.2 because its extensions are not built. Try: gem pristine hiredis --version 0.5.2 Ignoring hitimes-1.2.2 because its extensions are not built. Try: gem pristine hitimes --version 1.2.2 Ignoring http_parser.rb-0.6.0 because its extensions are not built. Try: gem pristine http_parser.rb --version 0.6.0 Ignoring nokogiri-1.6.8.1 because its extensions are not built. Try: gem pristine nokogiri --version 1.6.8.1 Ignoring nokogiri-1.6.8 because its extensions are not built. Try: gem pristine nokogiri --version 1.6.8 Ignoring puma-3.6.0 because its extensions are not built. Try: gem pristine puma --version 3.6.0 Ignoring stackprof-0.2.7 because its extensions are not built. Try: gem pristine stackprof --version 0.2.7 Ignoring thin-1.6.3 because its extensions are not built. Try: gem pristine thin --version 1.6.3 Ignoring unf_ext-0.0.7.2 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.7.2

and terminal error messages gem pristine bcrypt --version 3.1.9 ERROR: While executing gem ... (Gem::Exception) Failed to find gems ["bcrypt"] = 3.1.9

**Comment by trotzig** [comment]
I think you might get more luck posting this in the linter-scss-lint project: https://github.com/AtomLinter/linter-scss-lint/issues
