### ISSUE TITLE
Update Smacss

### ISSUE THREAD

**Issue by Yimiprod** [brigade/scss-lint#883]
Is it possible to update the `.smacss.txt` file to support new css attributes?
I've worked on it https://gist.github.com/Yimiprod/c9dadba643d54c56c660a80755b3deaf and looking for advice to update it.

By the way i don't find how to define a custom `.txt` file for scss-lint.

**Comment by trotzig** [comment]
What are the new attributes you're looking to add? Can you file a PR instead of the gist? I'll be happy to review it.

**Comment by Yimiprod** [comment]
Here's a PR https://github.com/brigade/scss-lint/pull/884
