### ISSUE TITLE
I can't dissable NoMisspelledProperties 

### ISSUE THREAD

**Issue by gabrielmanara** [brigade/scss-lint#885]
I'm using lost grid system and there are some properties like `lost-center`, `lost-column` that I need to use.
So I'm trying disable the lint no-misspelled-properties that way but doesn't work:
`NoMisspelledProperties:`
    `enabled: false`

**Comment by trotzig** [comment]
I can't find the `NoMisspelledProperties` linter here: https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md

Did you mean `PropertySpelling`?

**Comment by gabrielmanara** [comment]
@trotzig Thank you I changed this propertie `PropertySpelling` before but in my text editor (Sublime Text3) doesn't reflect. Now I cleaned the cache and works.

**Comment by trotzig** [comment]
Glad it worked out.
