### ISSUE TITLE
Release title

### ISSUE THREAD

**Issue by tysongach** [brigade/scss-lint#896]
The [release title for 0.53.0](https://github.com/brigade/scss-lint/releases/tag/v0.53.0) was mistakingly written as “HAML-lint 0.53.0”, instead of “SCSS-Lint 0.53.0.”

**Comment by sds** [comment]
Thanks for catching, @tysongach. Fixed!

**Comment by trotzig** [comment]
Lol, my bad! Thanks @sds!
