### ISSUE TITLE
Ignore node_modules in all projects

### ISSUE THREAD

**Issue by garyking** [brigade/scss-lint#947]
Is it possible to ignore folders, like node_modules, from the home dir config file?

I tried the following but it didn't work. In the `~/.scss-lint.yml` file, I put the following:

```
exclude:
  - '*.css'
  - 'node_modules/**'
```

This didn't work. It only worked if I put it in a project's `.scss-lint.yml` file. Is this intentional? I know the docs say the paths are relative to the config file. So this means that it's not possible to exclude `node_modules` for all projects, since it's definitely something that I don't mind being a global exclude?

**Comment by sds** [comment]
Duplicated of #516. Feel free to contribute to the discussion there, but at its core we are happy to add this if someone submits a pull request!
