### ISSUE TITLE
Migrate to sassc?

### ISSUE THREAD

**Issue by AlfredoRamos** [brigade/scss-lint#959]
Hi,

Have you considered migrating the library to [sassc](https://github.com/sass/sassc-ruby)? It seems to be a drop-in replacement for the deprecated [sass](https://github.com/sass/ruby-sass) gem.

Right now it works just right, but I would prefer not to use alternative NPM packages as the README says, in the case that in a future this gem is deprecated too.

**Comment by mprins** [comment]
sassc doesn't seem to provide a sass parser (which is required) and is only available on a limited number of platforms (eg. not on any of the BSD flavours last time I checked), sassc failed to run on jruby last time I checked, imo it's a major step back.

**Comment by AlfredoRamos** [comment]
I see, so the major problem is the parser, I was hoping something could be done with that gem.

Thanks.

**Comment by mprins** [comment]
the gem is only a wrapper around a C library
